import{useState}from"react";import{Card,CardContent}from"../../components/ui/card";import{Badge}from"../../components/ui/badge";import{Input}from"../../components/ui/input";import{Search,Wrench}from"lucide-react";
const calls=[{id:"TC-001",timestamp:"14:23:01",agent:"ComplianceBot",tool:"search_regulations",args:"query=GDPR Art.17",result:"success",latency:"234ms",tokens:45},{id:"TC-002",timestamp:"14:22:58",agent:"DataGuard",tool:"scan_pii",args:"table=customers",result:"success",latency:"156ms",tokens:0},{id:"TC-003",timestamp:"14:22:55",agent:"RiskAnalyzer",tool:"calculate_risk_score",args:"model_id=M-001",result:"success",latency:"89ms",tokens:0},{id:"TC-004",timestamp:"14:22:50",agent:"SupportBot",tool:"fetch_knowledge_base",args:"topic=billing",result:"error",latency:"5001ms",tokens:0},{id:"TC-005",timestamp:"14:22:45",agent:"LegalDraft",tool:"generate_clause",args:"type=NDA",result:"success",latency:"1890ms",tokens:234},{id:"TC-006",timestamp:"14:22:40",agent:"ComplianceBot",tool:"create_audit_log",args:"action=review",result:"success",latency:"23ms",tokens:0}];
const rc:Record<string,string>={success:"bg-green-500/20 text-green-400",error:"bg-red-500/20 text-red-400"};
export default function ToolCallMonitor(){const[search,setSearch]=useState("");const filtered=calls.filter(c=>c.tool.includes(search.toLowerCase())||c.agent.toLowerCase().includes(search.toLowerCase()));return(<div className="space-y-6">
  <div><h1 className="text-2xl font-bold">Tool Call Monitor</h1><p className="text-muted-foreground">Track all tool invocations across agents</p></div>
  <div className="grid grid-cols-4 gap-4">
    <Card><CardContent className="pt-4 text-center"><div className="text-3xl font-bold">{calls.length}</div><div className="text-sm text-muted-foreground">Total Calls</div></CardContent></Card>
    <Card><CardContent className="pt-4 text-center"><div className="text-3xl font-bold text-green-400">{calls.filter(c=>c.result==="success").length}</div><div className="text-sm text-muted-foreground">Successful</div></CardContent></Card>
    <Card><CardContent className="pt-4 text-center"><div className="text-3xl font-bold text-red-400">{calls.filter(c=>c.result==="error").length}</div><div className="text-sm text-muted-foreground">Errors</div></CardContent></Card>
    <Card><CardContent className="pt-4 text-center"><div className="text-3xl font-bold">{new Set(calls.map(c=>c.tool)).size}</div><div className="text-sm text-muted-foreground">Unique Tools</div></CardContent></Card>
  </div>
  <div className="relative"><Search className="absolute left-3 top-2.5 w-4 h-4 text-muted-foreground"/><Input placeholder="Search tools..." value={search} onChange={e=>setSearch(e.target.value)} className="pl-9"/></div>
  <Card><CardContent className="p-0"><table className="w-full"><thead><tr className="border-b border-border">
    <th className="text-left p-3 text-sm font-medium text-muted-foreground">Time</th><th className="text-left p-3 text-sm font-medium text-muted-foreground">Agent</th><th className="text-left p-3 text-sm font-medium text-muted-foreground">Tool</th><th className="text-left p-3 text-sm font-medium text-muted-foreground">Arguments</th><th className="text-left p-3 text-sm font-medium text-muted-foreground">Result</th><th className="text-left p-3 text-sm font-medium text-muted-foreground">Latency</th>
  </tr></thead><tbody>{filtered.map(c=>(
    <tr key={c.id} className="border-b border-border hover:bg-muted/50">
      <td className="p-3 text-xs font-mono text-muted-foreground">{c.timestamp}</td><td className="p-3 text-sm">{c.agent}</td><td className="p-3"><div className="flex items-center gap-1"><Wrench className="w-3 h-3 text-muted-foreground"/><span className="text-sm font-mono">{c.tool}</span></div></td><td className="p-3 text-xs font-mono text-muted-foreground">{c.args}</td><td className="p-3"><Badge className={rc[c.result]}>{c.result}</Badge></td><td className="p-3 text-xs font-mono">{c.latency}</td>
    </tr>
  ))}</tbody></table></CardContent></Card>
</div>);}
