INSERT INTO controls (framework_id, control_ref, name, description, severity)
SELECT f.id, v.ref, v.name, v.desc, v.sev FROM frameworks f,
(VALUES
('Clause 5.2','AI Policy & Objectives','Establish and maintain AI policy aligned with organizational objectives.','Medium'),
('Clause 6.1','AI Risk Assessment Process','Systematic identification and evaluation of AI-related risks.','Medium'),
('Clause 6.1.2','AI Impact Assessment','Assess potential impacts of AI systems on stakeholders.','Medium'),
('Clause 5.3','Roles & Responsibilities for AI','Define clear roles for AI governance and operations.','Medium'),
('Clause 8.2','AI System Lifecycle Management','Manage AI systems throughout their complete lifecycle.','Medium'),
('Clause 8.4','Data Quality for AI Systems','Ensure data used in AI systems meets quality requirements.','Medium'),
('Clause 8.5','AI System Validation','Validate AI systems meet specified requirements.','Medium'),
('Clause 8.6','AI Transparency Requirements','Ensure AI system decisions are transparent and explainable.','Medium'),
('Clause 8.7','Third-Party AI Components','Manage risks from third-party AI components and services.','Medium'),
('Clause 7.2','AI Competence & Awareness','Ensure personnel have necessary AI competencies.','Medium'),
('Clause 7.5','AI System Documentation','Maintain comprehensive documentation for AI systems.','Medium'),
('Clause 9.1','AI Performance Monitoring','Monitor and measure AI system performance continuously.','Medium'),
('Clause 9.2','Internal Audit for AI','Conduct regular internal audits of AI management system.','Medium'),
('Clause 9.3','Management Review','Review AI management system at planned intervals.','Medium'),
('Clause 10.1','Continual Improvement','Continuously improve AI management system effectiveness.','Medium'),
('Clause 10.2','Nonconformity & Corrective Action','Address nonconformities and implement corrective actions.','Medium'),
('Clause 7.4','AI Stakeholder Communication','Communicate AI-related information to stakeholders.','Medium'),
('Clause 4.1','Context of Organization','Understand organizational context for AI management.','Medium'),
('Clause 4.2','Stakeholder Needs','Identify needs and expectations of interested parties.','Medium'),
('Clause 4.3','AIMS Scope Definition','Define scope of AI management system.','Medium'),
('Clause 5.1','Leadership Commitment','Demonstrate leadership commitment to AI management.','Medium'),
('Clause 7.1','AI Resource Management','Provide resources needed for AI management system.','Medium'),
('Clause 8.1','Operational Planning','Plan and control AI operational processes.','Medium'),
('Annex A.2','AI Bias Mitigation','Assess and mitigate bias in AI systems.','Medium'),
('Annex A.3','AI Fairness Controls','Implement controls to ensure AI system fairness.','Medium'),
('Annex A.4','Explainability Requirements','Ensure AI decisions can be explained to stakeholders.','Medium'),
('Annex A.5','AI Safety Controls','Implement safety measures for AI system operation.','Medium'),
('Annex A.6','AI Security Controls','Protect AI systems from security threats.','Medium'),
('Annex A.7','AI Privacy Controls','Protect personal data in AI system processing.','Medium'),
('Annex A.8','Human Oversight of AI','Maintain meaningful human oversight of AI systems.','Medium'),
('Annex A.9','Accountability Framework','Establish accountability for AI system outcomes.','Medium'),
('Annex A.10','Societal Impact Assessment','Assess broader societal impacts of AI systems.','Medium'),
('Annex B.1','Training Data Governance','Govern the selection and use of AI training data.','Medium'),
('Annex B.2','Model Selection & Design','Govern AI model selection and design processes.','Medium'),
('Annex B.3','AI Testing & Evaluation','Test and evaluate AI systems before deployment.','Medium'),
('Annex B.4','Deployment Controls','Control AI system deployment processes.','Medium'),
('Annex B.5','Decommissioning Procedures','Safely decommission AI systems when needed.','Medium'),
('Annex B.6','AI Incident Management','Manage incidents related to AI system operation.','Medium'),
('Annex B.7','Supplier AI Risk','Manage AI-related risks from suppliers.','Medium'),
('Annex B.8','Regulatory Compliance Tracking','Track compliance with AI regulations.','Medium'),
('Annex C.1','Ethics Committee Governance','Govern AI ethics committee operations.','Medium'),
('Annex C.2','Stakeholder Engagement','Engage stakeholders in AI governance.','Medium'),
('Annex C.3','AI Knowledge Management','Manage organizational AI knowledge.','Medium'),
('Annex C.4','Cross-Border Data Transfer','Control cross-border AI data transfers.','Medium'),
('Annex C.5','System Inventory Management','Maintain inventory of all AI systems.','Medium')
) AS v(ref, name, desc, sev)
WHERE f.code='FW-001'
ON CONFLICT (framework_id, control_ref) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description;
INSERT INTO controls (framework_id, control_ref, name, description, severity)
SELECT f.id, v.ref, v.name, v.desc, v.sev FROM frameworks f,
(VALUES
('GOVERN 1.1','Legal & Regulatory Awareness','Maintain awareness of applicable AI laws and regulations.','Medium'),
('GOVERN 1.2','Risk Management Commitment','Demonstrate organizational commitment to AI risk management.','Medium'),
('GOVERN 1.3','AI Risk Processes','Establish processes for AI risk identification and management.','Medium'),
('GOVERN 1.4','Risk Management Integration','Integrate AI risk management with enterprise risk management.','Medium'),
('GOVERN 1.5','Organizational AI Policies','Develop and maintain organizational AI policies.','Medium'),
('GOVERN 1.6','Oversight Mechanisms','Establish mechanisms for AI system oversight.','Medium'),
('GOVERN 1.7','System Decommissioning','Define processes for AI system decommissioning.','Medium'),
('GOVERN 2.1','Roles & Responsibilities','Assign clear AI governance roles and responsibilities.','Medium'),
('GOVERN 2.2','Workforce Diversity','Ensure diversity in AI development and oversight teams.','Medium'),
('GOVERN 2.3','Executive Oversight','Maintain executive-level AI oversight.','Medium'),
('GOVERN 3.1','Decision-Making Processes','Establish AI-related decision-making processes.','Medium'),
('GOVERN 3.2','Stakeholder Feedback','Integrate stakeholder feedback into AI governance.','Medium'),
('GOVERN 4.1','Organizational Culture','Foster organizational culture supporting responsible AI.','Medium'),
('GOVERN 4.2','Training & Awareness','Provide AI training and awareness programs.','Medium'),
('GOVERN 4.3','Competency Assessment','Assess AI-related competencies across the organization.','Medium'),
('GOVERN 5.1','Third-Party Engagement','Manage third-party AI engagements and relationships.','Medium'),
('GOVERN 5.2','Supply Chain Risk','Manage AI supply chain risks.','Medium'),
('GOVERN 6.1','Metrics & Monitoring','Define and track AI governance metrics.','Medium'),
('GOVERN 6.2','Risk Tolerance Definition','Define organizational AI risk tolerance levels.','Medium'),
('MAP 1.1','Intended Purpose & Context','Document AI system intended purpose and context of use.','Medium'),
('MAP 1.2','Interdisciplinary Team','Assemble interdisciplinary teams for AI development.','Medium'),
('MAP 1.3','System Requirements','Define comprehensive AI system requirements.','Medium'),
('MAP 1.4','System Boundaries','Identify and document AI system boundaries.','Medium'),
('MAP 1.5','Assumptions Documentation','Document assumptions underlying AI systems.','Medium'),
('MAP 1.6','Stakeholder Identification','Identify all stakeholders affected by AI systems.','Medium'),
('MAP 2.1','Data Requirements','Define data requirements for AI systems.','Medium'),
('MAP 2.2','Data Quality Assessment','Assess quality of data used in AI systems.','Medium'),
('MAP 2.3','Data Representativeness','Ensure training data is representative.','Medium'),
('MAP 3.1','Benefits & Costs Analysis','Analyze benefits and costs of AI deployment.','Medium'),
('MAP 3.2','Societal Impact Assessment','Assess societal impacts of AI systems.','Medium'),
('MAP 3.3','Risk Identification','Identify risks associated with AI systems.','Medium'),
('MAP 3.4','Trustworthiness Characteristics','Define trustworthiness requirements for AI.','Medium'),
('MAP 3.5','Likelihood & Impact','Assess likelihood and impact of AI risks.','Medium'),
('MEASURE 1.1','Appropriate Metrics','Select appropriate metrics for AI measurement.','Medium'),
('MEASURE 1.2','Metric Thresholds','Establish thresholds for AI performance metrics.','Medium'),
('MEASURE 1.3','Measurement Approaches','Define approaches for measuring AI systems.','Medium'),
('MEASURE 2.1','Test & Evaluation','Conduct testing and evaluation of AI systems.','Medium'),
('MEASURE 2.2','Validation & Verification','Validate and verify AI system behavior.','Medium'),
('MEASURE 2.3','System Performance','Measure and track AI system performance.','Medium'),
('MEASURE 2.4','Bias & Fairness Testing','Test AI systems for bias and fairness.','Medium'),
('MEASURE 2.5','Privacy Testing','Test AI systems for privacy compliance.','Medium'),
('MEASURE 2.6','Security Testing','Test AI systems for security vulnerabilities.','Medium'),
('MEASURE 3.1','Deployment Monitoring','Monitor AI systems during deployment.','Medium'),
('MEASURE 3.2','Post-Deployment Assessment','Assess AI systems after deployment.','Medium'),
('MEASURE 3.3','Continuous Monitoring','Continuously monitor AI system behavior.','Medium'),
('MANAGE 1.1','Risk Treatment Plans','Develop and implement AI risk treatment plans.','Medium'),
('MANAGE 1.2','Risk Response Actions','Execute risk response actions for AI systems.','Medium'),
('MANAGE 2.1','Risk Escalation','Establish AI risk escalation procedures.','Medium'),
('MANAGE 3.1','Incident Response','Respond to AI-related incidents effectively.','Medium'),
('MANAGE 4.1','Risk Communication','Communicate AI risks to relevant stakeholders.','Medium')
) AS v(ref, name, desc, sev)
WHERE f.code='FW-002'
ON CONFLICT (framework_id, control_ref) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description;
INSERT INTO controls (framework_id, control_ref, name, description, severity)
SELECT f.id, v.ref, v.name, v.desc, v.sev FROM frameworks f,
(VALUES
('Art. 6','AI System Risk Classification','Classify all AI systems by risk level per EU AI Act categories.','Medium'),
('Art. 10','Data Governance for AI Training','Ensure training data quality relevance and representativeness.','Medium'),
('Art. 13','Transparency & Documentation','Provide transparent information about AI system capabilities.','Medium'),
('Art. 14','Human Oversight Mechanisms','Enable human oversight and intervention in AI decisions.','Medium'),
('Art. 15','Accuracy & Robustness','Ensure AI systems achieve appropriate accuracy and robustness.','Medium'),
('Art. 5','Prohibited AI Practices','Identify and prevent prohibited AI practices.','Medium'),
('Art. 8','High-Risk AI Requirements','Implement requirements for high-risk AI systems.','Medium'),
('Art. 9','Risk Management System','Establish risk management for high-risk AI systems.','Medium'),
('Art. 11','Technical Documentation','Maintain technical documentation for AI systems.','Medium'),
('Art. 12','Record-Keeping Requirements','Implement automatic logging for high-risk AI systems.','Medium'),
('Art. 43','Conformity Assessment','Conduct conformity assessments for high-risk AI.','Medium'),
('Art. 49','CE Marking & Registration','Ensure proper CE marking and EU database registration.','Medium'),
('Art. 72','Post-Market Monitoring','Establish post-market monitoring for AI systems.','Medium'),
('Art. 73','Serious Incident Reporting','Report serious incidents involving AI systems.','Medium'),
('Art. 53','General-Purpose AI Obligations','Comply with obligations for general-purpose AI models.','Medium'),
('Art. 55','Systemic Risk Assessment','Assess systemic risks of high-impact AI models.','Medium'),
('Art. 4','AI Literacy Requirements','Ensure AI literacy among staff operating AI systems.','Medium'),
('Art. 27','Fundamental Rights Impact','Assess impact on fundamental rights before deployment.','Medium'),
('Art. 50','Transparency for Users','Inform users when interacting with AI systems.','Medium'),
('Art. 26','Deployer Obligations','Fulfill obligations as AI system deployer.','Medium'),
('Art. 16','Provider Obligations','Fulfill obligations as AI system provider.','Medium'),
('Art. 22','Authorized Representative','Designate authorized representative where required.','Medium'),
('Art. 23','Importer Obligations','Fulfill obligations as AI system importer.','Medium'),
('Art. 24','Distributor Obligations','Fulfill obligations as AI system distributor.','Medium'),
('Art. 17','Quality Management System','Implement quality management system for AI.','Medium'),
('Art. 47','EU Declaration of Conformity','Prepare EU declaration of conformity.','Medium'),
('Art. 29','Notified Body Engagement','Engage notified bodies for conformity assessment.','Medium'),
('Art. 57','Sandbox Participation','Participate in AI regulatory sandboxes where applicable.','Medium'),
('Art. 7','Biometric AI Controls','Control use of biometric AI identification systems.','Medium'),
('Art. 50.3','Emotion Recognition Controls','Disclose emotion recognition AI system use.','Medium'),
('Art. 50.4','Deep Fake Disclosure','Disclose AI-generated or manipulated content.','Medium'),
('Art. 18','AI System Traceability','Ensure traceability of AI system decisions.','Medium'),
('Art. 20','Corrective Action Procedures','Implement corrective actions for non-conforming AI.','Medium'),
('Art. 74','Market Surveillance Cooperation','Cooperate with market surveillance authorities.','Medium'),
('Art. 56','Codes of Practice','Develop or adhere to AI codes of practice.','Medium'),
('Art. 10.5','Data Protection Compliance','Ensure AI data processing complies with GDPR.','Medium'),
('Art. 16.h','Accessibility Requirements','Ensure AI system accessibility for persons with disabilities.','Medium'),
('Art. 40','Environmental Sustainability','Consider environmental impact of AI systems.','Medium'),
('Art. 25','Cross-Border AI Deployment','Manage cross-border deployment requirements.','Medium'),
('Art. 21','AI System Withdrawal','Withdraw non-conforming AI systems from market.','Medium'),
('Art. 60','Testing in Real-World Conditions','Manage testing of AI in real-world conditions.','Medium'),
('Art. 61','Informed Consent for Testing','Obtain consent for real-world AI testing.','Medium'),
('Art. 28','Child Protection in AI','Protect children from harmful AI system effects.','Medium'),
('Art. 5.1c','Democratic Process Protection','Prevent AI manipulation of democratic processes.','Medium'),
('Art. 5.1c.2','Social Scoring Prevention','Prevent AI-based social scoring systems.','Medium'),
('Art. 26.7','Workplace AI Transparency','Inform workers about workplace AI systems.','Medium'),
('Annex III.5','Financial AI Risk Controls','Control AI risks in financial services.','Medium'),
('Annex III.1','Healthcare AI Validation','Validate AI systems used in healthcare.','Medium'),
('Annex III.2','Critical Infrastructure AI','Secure AI in critical infrastructure.','Medium'),
('Annex III.3','Education AI Safeguards','Safeguard AI use in education.','Medium'),
('Annex III.4','Employment AI Fairness','Ensure fairness in employment AI systems.','Medium'),
('Annex III.6','Law Enforcement AI Controls','Control AI use in law enforcement.','Medium'),
('Annex III.7','Immigration AI Controls','Control AI in immigration and border management.','Medium'),
('Annex III.8','Justice AI Safeguards','Safeguard AI use in justice administration.','Medium'),
('Art. 5.1d','Predictive Policing Controls','Control AI use in predictive policing.','Medium')
) AS v(ref, name, desc, sev)
WHERE f.code='FW-003'
ON CONFLICT (framework_id, control_ref) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description;
INSERT INTO controls (framework_id, control_ref, name, description, severity)
SELECT f.id, v.ref, v.name, v.desc, v.sev FROM frameworks f,
(VALUES
('Sec 2.1','Internal Governance','Establish internal governance structures for AI.','Medium'),
('Sec 2.2','AI Ethics Board','Create and maintain an AI ethics advisory board.','Medium'),
('Sec 2.3','Risk Assessment Framework','Implement risk assessment framework for AI.','Medium'),
('Sec 3.1','Algorithm Governance','Govern algorithm selection and deployment.','Medium'),
('Sec 3.2','Data Management','Manage data used in AI systems responsibly.','Medium'),
('Sec 3.3','Explainability','Ensure AI decisions are explainable to stakeholders.','Medium'),
('Sec 3.4','Repeatability & Reproducibility','Ensure AI outcomes are repeatable and reproducible.','Medium'),
('Sec 3.5','Traceability','Maintain traceability of AI decision processes.','Medium'),
('Sec 4.1','Human-in-the-Loop','Maintain human involvement in critical AI decisions.','Medium'),
('Sec 4.2','Human-over-the-Loop','Enable human override of AI system decisions.','Medium'),
('Sec 4.3','Human-out-of-the-Loop','Define criteria for autonomous AI operation.','Medium'),
('Sec 5.1','Stakeholder Interaction','Manage interactions with AI system stakeholders.','Medium'),
('Sec 5.2','Communication Strategy','Develop communication strategy for AI deployment.','Medium'),
('Sec 6.1','Operations Management','Manage AI system operations effectively.','Medium'),
('Sec 6.2','Performance Monitoring','Monitor AI system performance continuously.','Medium'),
('Sec 6.3','Incident Management','Manage incidents involving AI systems.','Medium'),
('Sec 7.1','Regular Review','Conduct regular reviews of AI governance.','Medium'),
('Sec 7.2','Continuous Improvement','Continuously improve AI governance practices.','Medium'),
('Sec 8.1','Industry Collaboration','Collaborate with industry on AI best practices.','Medium'),
('Sec 8.2','Public Trust Building','Build public trust in organizational AI use.','Medium'),
('Sec 3.6','Bias Detection & Mitigation','Detect and mitigate bias in AI systems.','Medium'),
('Sec 3.7','Model Validation','Validate AI models before production deployment.','Medium'),
('Sec 3.8','Data Privacy Protection','Protect personal data in AI processing.','Medium'),
('Sec 3.9','Security Measures','Implement security measures for AI systems.','Medium'),
('Sec 6.4','Vendor Management','Manage AI vendors and third-party services.','Medium'),
('Sec 5.3','Training Programs','Implement AI training programs for staff.','Medium'),
('Sec 6.5','Documentation Standards','Maintain documentation standards for AI systems.','Medium'),
('Sec 2.4','Accountability Measures','Establish accountability for AI system outcomes.','Medium'),
('Sec 2.5','Impact Assessment','Assess impact of AI systems on communities.','Medium'),
('Sec 7.3','Compliance Monitoring','Monitor compliance with AI governance requirements.','Medium')
) AS v(ref, name, desc, sev)
WHERE f.code='FW-004'
ON CONFLICT (framework_id, control_ref) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description;
INSERT INTO controls (framework_id, control_ref, name, description, severity)
SELECT f.id, v.ref, v.name, v.desc, v.sev FROM frameworks f,
(VALUES
('LLM01','Prompt Injection Prevention','Prevent prompt injection attacks on LLM systems.','Medium'),
('LLM02','Insecure Output Handling','Handle LLM outputs securely to prevent exploitation.','Medium'),
('LLM03','Training Data Poisoning Prevention','Prevent poisoning of LLM training data.','Medium'),
('LLM04','Model Denial of Service','Protect LLMs from denial of service attacks.','Medium'),
('LLM05','Supply Chain Vulnerability Management','Manage vulnerabilities in LLM supply chain.','Medium'),
('LLM06','Sensitive Information Disclosure','Prevent LLMs from disclosing sensitive information.','Medium'),
('LLM07','Insecure Plugin Design','Secure LLM plugin design and implementation.','Medium'),
('LLM08','Excessive Agency Prevention','Prevent LLMs from taking excessive autonomous actions.','Medium'),
('LLM09','Overreliance Mitigation','Mitigate risks from overreliance on LLM outputs.','Medium'),
('LLM10','Model Theft Prevention','Prevent theft of LLM models and weights.','Medium'),
('LLM01.1','Input Validation Controls','Validate and sanitize all inputs to LLM systems.','Medium'),
('LLM02.1','Output Encoding','Encode LLM outputs before rendering in applications.','Medium'),
('LLM03.1','Data Provenance Tracking','Track provenance of all LLM training data.','Medium'),
('LLM04.1','Rate Limiting','Implement rate limiting for LLM API requests.','Medium'),
('LLM05.1','Dependency Scanning','Scan LLM dependencies for vulnerabilities.','Medium'),
('LLM06.1','PII Filtering','Filter personally identifiable information from LLM responses.','Medium'),
('LLM07.1','Plugin Sandboxing','Sandbox LLM plugins to limit access scope.','Medium'),
('LLM08.1','Action Approval Workflows','Require approval for consequential LLM actions.','Medium'),
('LLM09.1','Confidence Scoring','Implement confidence scoring for LLM outputs.','Medium'),
('LLM10.1','Model Access Controls','Restrict access to LLM model artifacts.','Medium'),
('LLM01.2','Context Window Protection','Protect LLM context window from manipulation.','Medium'),
('LLM02.2','Response Filtering','Filter LLM responses for harmful content.','Medium'),
('LLM03.2','Training Pipeline Security','Secure the LLM training data pipeline.','Medium'),
('LLM04.2','Resource Monitoring','Monitor LLM resource consumption patterns.','Medium'),
('LLM05.2','Component Verification','Verify integrity of LLM components.','Medium'),
('LLM06.2','Data Loss Prevention','Implement DLP controls for LLM outputs.','Medium'),
('LLM07.2','API Security Controls','Secure APIs used by LLM plugins.','Medium'),
('LLM08.2','Permission Boundaries','Enforce strict permission boundaries for LLM actions.','Medium'),
('LLM09.2','Human Review Triggers','Trigger human review for uncertain LLM outputs.','Medium'),
('LLM10.2','Model Watermarking','Implement watermarking for LLM model protection.','Medium'),
('LLM01.3','Indirect Injection Defense','Defend against indirect prompt injection attacks.','Medium'),
('LLM02.3','Content Safety Filters','Apply content safety filters to LLM outputs.','Medium'),
('LLM03.3','Fine-Tuning Security','Secure LLM fine-tuning processes.','Medium'),
('LLM04.3','Inference Optimization','Optimize LLM inference for resource efficiency.','Medium'),
('LLM05.3','Version Control','Maintain version control for LLM components.','Medium')
) AS v(ref, name, desc, sev)
WHERE f.code='FW-005'
ON CONFLICT (framework_id, control_ref) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description;
INSERT INTO controls (framework_id, control_ref, name, description, severity)
SELECT f.id, v.ref, v.name, v.desc, v.sev FROM frameworks f,
(VALUES
('Prin 1.1','Inclusive Growth','Ensure AI contributes to inclusive growth and sustainable development.','Medium'),
('Prin 1.2','Well-Being Enhancement','Design AI to enhance individual and societal well-being.','Medium'),
('Prin 2.1','Human-Centred Values','Embed human-centred values in AI systems.','Medium'),
('Prin 2.2','Fairness & Non-Discrimination','Prevent unfair discrimination by AI systems.','Medium'),
('Prin 3.1','Transparency & Explainability','Ensure transparency in AI system operations.','Medium'),
('Prin 3.2','Meaningful Information Disclosure','Disclose meaningful information about AI systems.','Medium'),
('Prin 4.1','Robustness & Safety','Ensure AI systems are robust and safe.','Medium'),
('Prin 4.2','Security & Privacy','Protect security and privacy in AI systems.','Medium'),
('Prin 4.3','Risk Management','Manage risks throughout AI system lifecycle.','Medium'),
('Prin 5.1','Accountability','Ensure accountability for AI system outcomes.','Medium'),
('Prin 5.2','Responsible Stewardship','Practice responsible stewardship of AI.','Medium'),
('Rec 1.1','Investment in AI Research','Invest in AI research and development.','Medium'),
('Rec 2.1','Digital Ecosystem for AI','Foster a digital ecosystem for trustworthy AI.','Medium'),
('Rec 3.1','AI Policy Environment','Shape an enabling policy environment for AI.','Medium'),
('Rec 4.1','Building Human Capacity','Build human capacity for AI adoption.','Medium'),
('Rec 5.1','International Cooperation','Promote international cooperation on AI governance.','Medium'),
('Prin 2.3','Stakeholder Participation','Enable stakeholder participation in AI governance.','Medium'),
('Prin 1.3','Environmental Impact','Consider environmental impact of AI systems.','Medium'),
('Prin 1.4','Digital Inclusion','Promote digital inclusion through AI.','Medium'),
('Rec 1.2','Innovation Promotion','Promote AI innovation while managing risks.','Medium'),
('Rec 2.2','Data Access & Sharing','Enable responsible data access and sharing for AI.','Medium'),
('Rec 4.2','Workforce Transition','Support workforce transition in AI era.','Medium'),
('Rec 3.2','Multi-Stakeholder Governance','Implement multi-stakeholder AI governance.','Medium'),
('Rec 3.3','Regulatory Frameworks','Develop appropriate regulatory frameworks for AI.','Medium'),
('Rec 2.3','Trustworthy AI Standards','Develop standards for trustworthy AI.','Medium')
) AS v(ref, name, desc, sev)
WHERE f.code='FW-006'
ON CONFLICT (framework_id, control_ref) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description;
INSERT INTO controls (framework_id, control_ref, name, description, severity)
SELECT f.id, v.ref, v.name, v.desc, v.sev FROM frameworks f,
(VALUES
('Art. 6','Lawfulness of Processing','Ensure lawful basis for personal data processing.','Medium'),
('Art. 5.1b','Purpose Limitation','Limit data processing to specified purposes.','Medium'),
('Art. 5.1c','Data Minimization','Collect only necessary personal data.','Medium'),
('Art. 5.1d','Accuracy of Data','Maintain accuracy of personal data.','Medium'),
('Art. 5.1e','Storage Limitation','Limit storage duration of personal data.','Medium'),
('Art. 5.1f','Integrity & Confidentiality','Ensure security of personal data processing.','Medium'),
('Art. 7','Consent Management','Obtain and manage valid data subject consent.','Medium'),
('Art. 15','Right to Access','Enable data subjects to access their personal data.','Medium'),
('Art. 16','Right to Rectification','Enable data subjects to correct inaccurate data.','Medium'),
('Art. 17','Right to Erasure','Enable data subjects to request data deletion.','Medium'),
('Art. 20','Right to Portability','Enable data subjects to transfer their data.','Medium'),
('Art. 21','Right to Object','Enable data subjects to object to processing.','Medium'),
('Art. 22','Automated Decision Rights','Ensure rights around automated decision-making.','Medium'),
('Art. 25','Data Protection by Design','Implement data protection by design and default.','Medium'),
('Art. 35','Data Protection Impact Assessment','Conduct DPIAs for high-risk processing.','Medium'),
('Art. 33','Data Breach Notification','Notify supervisory authority of data breaches.','Medium'),
('Art. 34','Data Breach Communication','Communicate data breaches to affected individuals.','Medium'),
('Art. 37','DPO Appointment','Appoint Data Protection Officer where required.','Medium'),
('Art. 30','Records of Processing','Maintain records of processing activities.','Medium'),
('Art. 46','Cross-Border Transfer Safeguards','Implement safeguards for international transfers.','Medium'),
('Art. 28','Processor Agreements','Establish data processing agreements.','Medium'),
('Art. 26','Joint Controller Agreements','Establish joint controller arrangements.','Medium'),
('Art. 13','Privacy Notice Requirements','Provide transparent privacy notices.','Medium'),
('Art. 8','Children Data Protection','Protect personal data of children.','Medium'),
('Art. 9','Special Category Data','Control processing of special category data.','Medium'),
('Art. 31','Supervisory Authority Cooperation','Cooperate with supervisory authorities.','Medium'),
('Art. 42','Data Protection Certification','Obtain data protection certifications.','Medium'),
('Art. 40','Code of Conduct Adherence','Adhere to approved codes of conduct.','Medium'),
('Art. 18','Right to Restriction','Enable data subjects to restrict processing.','Medium'),
('Art. 6.1f','Legitimate Interest Assessment','Conduct legitimate interest assessments.','Medium'),
('Art. 12','Transparency of Processing','Ensure transparent communication about processing.','Medium'),
('Art. 32','Data Security Measures','Implement appropriate technical security measures.','Medium'),
('Art. 28.2','Sub-Processor Management','Manage and authorize sub-processors.','Medium'),
('Art. 49','International Transfer Mechanisms','Implement derogations for international transfers.','Medium'),
('Art. 12.3','Data Subject Request Handling','Handle data subject requests within timeframes.','Medium'),
('Art. 25.2','Privacy by Default','Implement privacy by default in data processing.','Medium'),
('Art. 36','Consultation with Authority','Consult supervisory authority for high-risk processing.','Medium'),
('Art. 27','Representative Appointment','Appoint representative in EU where required.','Medium'),
('Art. 88','Employee Data Protection','Protect employee personal data in employment.','Medium'),
('Art. 89','Research Data Safeguards','Safeguard data used for research purposes.','Medium')
) AS v(ref, name, desc, sev)
WHERE f.code='FW-007'
ON CONFLICT (framework_id, control_ref) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description;
INSERT INTO controls (framework_id, control_ref, name, description, severity)
SELECT f.id, v.ref, v.name, v.desc, v.sev FROM frameworks f,
(VALUES
('Val 1.1','Proportionality & Do No Harm','Ensure AI use is proportionate and does no harm.','Medium'),
('Val 1.2','Safety & Security','Ensure AI systems are safe and secure.','Medium'),
('Val 2.1','Right to Privacy','Protect right to privacy in AI systems.','Medium'),
('Val 2.2','Data Protection in AI','Implement data protection measures for AI.','Medium'),
('Val 3.1','Multi-Stakeholder Governance','Enable multi-stakeholder and adaptive AI governance.','Medium'),
('Val 3.2','Transparency & Explainability','Ensure AI transparency and explainability.','Medium'),
('Val 4.1','Responsibility & Accountability','Establish responsibility and accountability for AI.','Medium'),
('Val 4.2','Human Oversight & Determination','Maintain human oversight and determination over AI.','Medium'),
('Val 5.1','Awareness & Literacy','Promote AI awareness and literacy.','Medium'),
('Val 5.2','Inclusiveness & Equity','Ensure AI systems are inclusive and equitable.','Medium'),
('Val 5.3','Gender Equality in AI','Promote gender equality in AI development and use.','Medium'),
('Val 5.4','Cultural Diversity','Respect cultural diversity in AI systems.','Medium'),
('Val 6.1','Environment & Ecosystem','Protect environment and ecosystems from AI impacts.','Medium'),
('Val 6.2','AI for Sustainable Development','Use AI to support sustainable development goals.','Medium'),
('Val 7.1','Peace & Justice','Use AI to promote peace and justice.','Medium'),
('Val 7.2','Democratic Participation','Enable democratic participation through AI governance.','Medium'),
('Pol 1.1','AI Readiness Assessment','Assess organizational readiness for ethical AI.','Medium'),
('Pol 1.2','Impact Assessment Framework','Implement ethical impact assessment for AI.','Medium'),
('Pol 2.1','AI Governance Structure','Establish AI governance structures.','Medium'),
('Pol 3.1','International Cooperation','Promote international cooperation on AI ethics.','Medium'),
('Pol 4.1','Education & Research','Support AI ethics education and research.','Medium'),
('Pol 5.1','Health Sector AI Ethics','Apply AI ethics principles in health sector.','Medium'),
('Pol 5.2','Communication & Media AI','Apply AI ethics in communication and media.','Medium'),
('Pol 5.3','Economic Sector AI Ethics','Apply AI ethics in economic activities.','Medium'),
('Pol 5.4','Science & Technology AI','Apply AI ethics in science and technology.','Medium'),
('Val 5.5','Indigenous Knowledge Protection','Protect indigenous knowledge in AI systems.','Medium'),
('Val 7.3','Conflict Prevention','Prevent AI use in conflict escalation.','Medium'),
('Val 5.6','Digital Divide Reduction','Reduce digital divide through AI governance.','Medium'),
('Val 6.3','Water & Food Security AI','Apply AI ethics to water and food security.','Medium'),
('Val 6.4','Climate Action AI','Use AI responsibly for climate action.','Medium')
) AS v(ref, name, desc, sev)
WHERE f.code='FW-008'
ON CONFLICT (framework_id, control_ref) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description;
INSERT INTO controls (framework_id, control_ref, name, description, severity)
SELECT f.id, v.ref, v.name, v.desc, v.sev FROM frameworks f,
(VALUES
('SAIF 1.1','Secure AI Development Lifecycle','Implement security throughout AI development lifecycle.','Medium'),
('SAIF 1.2','AI Model Security Assessment','Assess security of AI models regularly.','Medium'),
('SAIF 2.1','Training Data Security','Secure AI training data from unauthorized access.','Medium'),
('SAIF 2.2','Model Poisoning Prevention','Prevent poisoning of AI models through data or training.','Medium'),
('SAIF 2.3','Adversarial Robustness Testing','Test AI systems against adversarial attacks.','Medium'),
('SAIF 3.1','AI Supply Chain Security','Secure the AI model and component supply chain.','Medium'),
('SAIF 3.2','Model Integrity Verification','Verify integrity of AI models in production.','Medium'),
('SAIF 4.1','Inference Security Controls','Secure AI inference endpoints and pipelines.','Medium'),
('SAIF 4.2','API Security for AI','Implement security controls for AI APIs.','Medium'),
('SAIF 4.3','AI Access Control','Implement authentication and access control for AI.','Medium'),
('SAIF 5.1','AI Monitoring & Detection','Monitor AI systems for security anomalies.','Medium'),
('SAIF 5.2','AI Incident Response','Establish incident response procedures for AI security.','Medium'),
('SAIF 5.3','Red Team Testing for AI','Conduct red team exercises targeting AI systems.','Medium'),
('SAIF 6.1','Model Extraction Prevention','Prevent unauthorized extraction of AI models.','Medium'),
('SAIF 6.2','Data Exfiltration Prevention','Prevent data exfiltration through AI systems.','Medium'),
('SAIF 7.1','Privacy-Preserving AI','Implement privacy-preserving techniques in AI.','Medium'),
('SAIF 7.2','Federated Learning Security','Secure federated learning implementations.','Medium'),
('SAIF 8.1','AI Vulnerability Management','Manage vulnerabilities in AI systems.','Medium'),
('SAIF 8.2','Patch Management for AI','Implement patch management for AI components.','Medium'),
('SAIF 9.1','Secure Model Deployment','Deploy AI models securely to production.','Medium'),
('SAIF 9.2','Container Security for AI','Secure containers running AI workloads.','Medium'),
('SAIF 10.1','AI Network Security','Implement network security for AI infrastructure.','Medium'),
('SAIF 10.2','Encryption for AI Data','Encrypt AI data at rest and in transit.','Medium'),
('SAIF 11.1','AI Audit Logging','Maintain comprehensive audit logs for AI systems.','Medium'),
('SAIF 11.2','Compliance Automation','Automate AI security compliance checks.','Medium'),
('SAIF 12.1','Third-Party AI Security','Assess security of third-party AI components.','Medium'),
('SAIF 12.2','AI Security Training','Train staff on AI security best practices.','Medium'),
('SAIF 13.1','Secure Prompt Engineering','Implement secure prompt engineering practices.','Medium'),
('SAIF 13.2','Output Sanitization','Sanitize AI system outputs before delivery.','Medium'),
('SAIF 14.1','Model Rollback Procedures','Establish procedures for AI model rollback.','Medium'),
('SAIF 14.2','AI Disaster Recovery','Implement disaster recovery for AI systems.','Medium'),
('SAIF 15.1','Threat Intelligence for AI','Integrate threat intelligence for AI security.','Medium'),
('SAIF 15.2','AI Security Metrics','Define and track AI security metrics.','Medium'),
('SAIF 16.1','Zero Trust for AI','Apply zero trust principles to AI infrastructure.','Medium'),
('SAIF 16.2','AI Secrets Management','Manage secrets and credentials for AI systems.','Medium')
) AS v(ref, name, desc, sev)
WHERE f.code='FW-009'
ON CONFLICT (framework_id, control_ref) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description;
