INSERT INTO controls (framework_id, control_ref, name, description, severity)
SELECT f.id, v.ref, v.name, v.desc, v.sev FROM frameworks f,
(VALUES
('GOVERN 1.1','Legal & Regulatory Awareness','Maintain awareness of applicable AI laws and regulations.','Medium'),
('GOVERN 1.2','Risk Management Commitment','Demonstrate organizational commitment to AI risk management.','Medium'),
('GOVERN 1.3','AI Risk Processes','Establish processes for AI risk identification and management.','Medium'),
('GOVERN 1.4','Risk Management Integration','Integrate AI risk management with enterprise risk management.','Medium'),
('GOVERN 1.5','Organizational AI Policies','Develop and maintain organizational AI policies.','Medium'),
('GOVERN 1.6','Oversight Mechanisms','Establish mechanisms for AI system oversight.','Medium'),
('GOVERN 1.7','System Decommissioning','Define processes for AI system decommissioning.','Medium'),
('GOVERN 2.1','Roles & Responsibilities','Assign clear AI governance roles and responsibilities.','Medium'),
('GOVERN 2.2','Workforce Diversity','Ensure diversity in AI development and oversight teams.','Medium'),
('GOVERN 2.3','Executive Oversight','Maintain executive-level AI oversight.','Medium'),
('GOVERN 3.1','Decision-Making Processes','Establish AI-related decision-making processes.','Medium'),
('GOVERN 3.2','Stakeholder Feedback','Integrate stakeholder feedback into AI governance.','Medium'),
('GOVERN 4.1','Organizational Culture','Foster organizational culture supporting responsible AI.','Medium'),
('GOVERN 4.2','Training & Awareness','Provide AI training and awareness programs.','Medium'),
('GOVERN 4.3','Competency Assessment','Assess AI-related competencies across the organization.','Medium'),
('GOVERN 5.1','Third-Party Engagement','Manage third-party AI engagements and relationships.','Medium'),
('GOVERN 5.2','Supply Chain Risk','Manage AI supply chain risks.','Medium'),
('GOVERN 6.1','Metrics & Monitoring','Define and track AI governance metrics.','Medium'),
('GOVERN 6.2','Risk Tolerance Definition','Define organizational AI risk tolerance levels.','Medium'),
('MAP 1.1','Intended Purpose & Context','Document AI system intended purpose and context of use.','Medium'),
('MAP 1.2','Interdisciplinary Team','Assemble interdisciplinary teams for AI development.','Medium'),
('MAP 1.3','System Requirements','Define comprehensive AI system requirements.','Medium'),
('MAP 1.4','System Boundaries','Identify and document AI system boundaries.','Medium'),
('MAP 1.5','Assumptions Documentation','Document assumptions underlying AI systems.','Medium'),
('MAP 1.6','Stakeholder Identification','Identify all stakeholders affected by AI systems.','Medium'),
('MAP 2.1','Data Requirements','Define data requirements for AI systems.','Medium'),
('MAP 2.2','Data Quality Assessment','Assess quality of data used in AI systems.','Medium'),
('MAP 2.3','Data Representativeness','Ensure training data is representative.','Medium'),
('MAP 3.1','Benefits & Costs Analysis','Analyze benefits and costs of AI deployment.','Medium'),
('MAP 3.2','Societal Impact Assessment','Assess societal impacts of AI systems.','Medium'),
('MAP 3.3','Risk Identification','Identify risks associated with AI systems.','Medium'),
('MAP 3.4','Trustworthiness Characteristics','Define trustworthiness requirements for AI.','Medium'),
('MAP 3.5','Likelihood & Impact','Assess likelihood and impact of AI risks.','Medium'),
('MEASURE 1.1','Appropriate Metrics','Select appropriate metrics for AI measurement.','Medium'),
('MEASURE 1.2','Metric Thresholds','Establish thresholds for AI performance metrics.','Medium'),
('MEASURE 1.3','Measurement Approaches','Define approaches for measuring AI systems.','Medium'),
('MEASURE 2.1','Test & Evaluation','Conduct testing and evaluation of AI systems.','Medium'),
('MEASURE 2.2','Validation & Verification','Validate and verify AI system behavior.','Medium'),
('MEASURE 2.3','System Performance','Measure and track AI system performance.','Medium'),
('MEASURE 2.4','Bias & Fairness Testing','Test AI systems for bias and fairness.','Medium'),
('MEASURE 2.5','Privacy Testing','Test AI systems for privacy compliance.','Medium'),
('MEASURE 2.6','Security Testing','Test AI systems for security vulnerabilities.','Medium'),
('MEASURE 3.1','Deployment Monitoring','Monitor AI systems during deployment.','Medium'),
('MEASURE 3.2','Post-Deployment Assessment','Assess AI systems after deployment.','Medium'),
('MEASURE 3.3','Continuous Monitoring','Continuously monitor AI system behavior.','Medium'),
('MANAGE 1.1','Risk Treatment Plans','Develop and implement AI risk treatment plans.','Medium'),
('MANAGE 1.2','Risk Response Actions','Execute risk response actions for AI systems.','Medium'),
('MANAGE 2.1','Risk Escalation','Establish AI risk escalation procedures.','Medium'),
('MANAGE 3.1','Incident Response','Respond to AI-related incidents effectively.','Medium'),
('MANAGE 4.1','Risk Communication','Communicate AI risks to relevant stakeholders.','Medium')
) AS v(ref, name, desc, sev)
WHERE f.code='FW-002'
ON CONFLICT (framework_id, control_ref) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description;
