INSERT INTO controls (framework_id, control_ref, name, description, severity)
SELECT f.id, v.ref, v.name, v.desc, v.sev FROM frameworks f,
(VALUES
('LLM01','Prompt Injection Prevention','Prevent prompt injection attacks on LLM systems.','Medium'),
('LLM02','Insecure Output Handling','Handle LLM outputs securely to prevent exploitation.','Medium'),
('LLM03','Training Data Poisoning Prevention','Prevent poisoning of LLM training data.','Medium'),
('LLM04','Model Denial of Service','Protect LLMs from denial of service attacks.','Medium'),
('LLM05','Supply Chain Vulnerability Management','Manage vulnerabilities in LLM supply chain.','Medium'),
('LLM06','Sensitive Information Disclosure','Prevent LLMs from disclosing sensitive information.','Medium'),
('LLM07','Insecure Plugin Design','Secure LLM plugin design and implementation.','Medium'),
('LLM08','Excessive Agency Prevention','Prevent LLMs from taking excessive autonomous actions.','Medium'),
('LLM09','Overreliance Mitigation','Mitigate risks from overreliance on LLM outputs.','Medium'),
('LLM10','Model Theft Prevention','Prevent theft of LLM models and weights.','Medium'),
('LLM01.1','Input Validation Controls','Validate and sanitize all inputs to LLM systems.','Medium'),
('LLM02.1','Output Encoding','Encode LLM outputs before rendering in applications.','Medium'),
('LLM03.1','Data Provenance Tracking','Track provenance of all LLM training data.','Medium'),
('LLM04.1','Rate Limiting','Implement rate limiting for LLM API requests.','Medium'),
('LLM05.1','Dependency Scanning','Scan LLM dependencies for vulnerabilities.','Medium'),
('LLM06.1','PII Filtering','Filter personally identifiable information from LLM responses.','Medium'),
('LLM07.1','Plugin Sandboxing','Sandbox LLM plugins to limit access scope.','Medium'),
('LLM08.1','Action Approval Workflows','Require approval for consequential LLM actions.','Medium'),
('LLM09.1','Confidence Scoring','Implement confidence scoring for LLM outputs.','Medium'),
('LLM10.1','Model Access Controls','Restrict access to LLM model artifacts.','Medium'),
('LLM01.2','Context Window Protection','Protect LLM context window from manipulation.','Medium'),
('LLM02.2','Response Filtering','Filter LLM responses for harmful content.','Medium'),
('LLM03.2','Training Pipeline Security','Secure the LLM training data pipeline.','Medium'),
('LLM04.2','Resource Monitoring','Monitor LLM resource consumption patterns.','Medium'),
('LLM05.2','Component Verification','Verify integrity of LLM components.','Medium'),
('LLM06.2','Data Loss Prevention','Implement DLP controls for LLM outputs.','Medium'),
('LLM07.2','API Security Controls','Secure APIs used by LLM plugins.','Medium'),
('LLM08.2','Permission Boundaries','Enforce strict permission boundaries for LLM actions.','Medium'),
('LLM09.2','Human Review Triggers','Trigger human review for uncertain LLM outputs.','Medium'),
('LLM10.2','Model Watermarking','Implement watermarking for LLM model protection.','Medium'),
('LLM01.3','Indirect Injection Defense','Defend against indirect prompt injection attacks.','Medium'),
('LLM02.3','Content Safety Filters','Apply content safety filters to LLM outputs.','Medium'),
('LLM03.3','Fine-Tuning Security','Secure LLM fine-tuning processes.','Medium'),
('LLM04.3','Inference Optimization','Optimize LLM inference for resource efficiency.','Medium'),
('LLM05.3','Version Control','Maintain version control for LLM components.','Medium')
) AS v(ref, name, desc, sev)
WHERE f.code='FW-005'
ON CONFLICT (framework_id, control_ref) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description;
