// Phase 5 - FIX 1: Complete type definitions
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      organizations: { Row: { id: string; name: string; slug: string; tier: string | null; created_at: string; updated_at: string }; Insert: Partial<Database["public"]["Tables"]["organizations"]["Row"]> & { name: string; slug: string }; Update: Partial<Database["public"]["Tables"]["organizations"]["Row"]> };
      profiles: { Row: { id: string; org_id: string | null; email: string; full_name: string | null; role: string; avatar_url: string | null; created_at: string }; Insert: Partial<Database["public"]["Tables"]["profiles"]["Row"]> & { id: string; email: string }; Update: Partial<Database["public"]["Tables"]["profiles"]["Row"]> };
      models: { Row: { id: string; org_id: string; name: string; version: string | null; status: string; risk_tier: string | null; owner_id: string | null; framework: string | null; created_at: string; updated_at: string }; Insert: Partial<Database["public"]["Tables"]["models"]["Row"]> & { org_id: string; name: string; status: string }; Update: Partial<Database["public"]["Tables"]["models"]["Row"]> };
      risks: { Row: { id: string; org_id: string; title: string; description: string | null; severity: string; likelihood: string | null; status: string; owner_id: string | null; mitigation: string | null; created_at: string; updated_at: string }; Insert: Partial<Database["public"]["Tables"]["risks"]["Row"]> & { org_id: string; title: string; severity: string; status: string }; Update: Partial<Database["public"]["Tables"]["risks"]["Row"]> };
      controls: { Row: { id: string; org_id: string; framework: string; control_id: string; title: string; description: string | null; status: string; owner_id: string | null; evidence_count: number; created_at: string; updated_at: string }; Insert: Partial<Database["public"]["Tables"]["controls"]["Row"]> & { org_id: string; framework: string; control_id: string; title: string; status: string }; Update: Partial<Database["public"]["Tables"]["controls"]["Row"]> };
      evidence: { Row: { id: string; org_id: string; control_id: string | null; title: string; type: string | null; storage_path: string | null; sha256: string | null; uploaded_by: string | null; created_at: string }; Insert: Partial<Database["public"]["Tables"]["evidence"]["Row"]> & { org_id: string; title: string }; Update: Partial<Database["public"]["Tables"]["evidence"]["Row"]> };
      audit_log: { Row: { id: string; org_id: string; actor_id: string | null; action: string; entity_type: string; entity_id: string | null; metadata: Json | null; sha256: string | null; created_at: string }; Insert: Partial<Database["public"]["Tables"]["audit_log"]["Row"]> & { org_id: string; action: string; entity_type: string }; Update: Partial<Database["public"]["Tables"]["audit_log"]["Row"]> };
      bias_audits: { Row: { id: string; org_id: string; model_id: string; dataset: string | null; framework: string | null; score: number | null; result: string | null; protected_attrs: Json | null; triggered_by: string | null; created_at: string }; Insert: Partial<Database["public"]["Tables"]["bias_audits"]["Row"]> & { org_id: string; model_id: string }; Update: Partial<Database["public"]["Tables"]["bias_audits"]["Row"]> };
      notifications: { Row: { id: string; org_id: string; user_id: string | null; type: string; title: string; body: string | null; read: boolean; created_at: string }; Insert: Partial<Database["public"]["Tables"]["notifications"]["Row"]> & { org_id: string; type: string; title: string }; Update: Partial<Database["public"]["Tables"]["notifications"]["Row"]> };
      guardrails: { Row: { id: string; org_id: string; name: string; type: string; rules: Json | null; enabled: boolean; created_at: string; updated_at: string }; Insert: Partial<Database["public"]["Tables"]["guardrails"]["Row"]> & { org_id: string; name: string; type: string }; Update: Partial<Database["public"]["Tables"]["guardrails"]["Row"]> };
      hitl_queue: { Row: { id: string; org_id: string; entity_type: string; entity_id: string; reason: string | null; status: string; assignee_id: string | null; resolution: string | null; created_at: string; resolved_at: string | null }; Insert: Partial<Database["public"]["Tables"]["hitl_queue"]["Row"]> & { org_id: string; entity_type: string; entity_id: string; status: string }; Update: Partial<Database["public"]["Tables"]["hitl_queue"]["Row"]> };
      vendors: { Row: { id: string; org_id: string; name: string; tier: string | null; status: string; risk_score: number | null; review_date: string | null; created_at: string; updated_at: string }; Insert: Partial<Database["public"]["Tables"]["vendors"]["Row"]> & { org_id: string; name: string; status: string }; Update: Partial<Database["public"]["Tables"]["vendors"]["Row"]> };
      use_cases: { Row: { id: string; org_id: string; title: string; description: string | null; status: string; risk_tier: string | null; owner_id: string | null; created_at: string; updated_at: string }; Insert: Partial<Database["public"]["Tables"]["use_cases"]["Row"]> & { org_id: string; title: string; status: string }; Update: Partial<Database["public"]["Tables"]["use_cases"]["Row"]> };
      prompts: { Row: { id: string; org_id: string; name: string; content: string; version: string | null; tags: string[] | null; created_by: string | null; created_at: string; updated_at: string }; Insert: Partial<Database["public"]["Tables"]["prompts"]["Row"]> & { org_id: string; name: string; content: string }; Update: Partial<Database["public"]["Tables"]["prompts"]["Row"]> };
      evaluations: { Row: { id: string; org_id: string; model_id: string | null; suite: string | null; score: number | null; status: string; results: Json | null; created_at: string }; Insert: Partial<Database["public"]["Tables"]["evaluations"]["Row"]> & { org_id: string; status: string }; Update: Partial<Database["public"]["Tables"]["evaluations"]["Row"]> };
      incidents: { Row: { id: string; org_id: string; title: string; severity: string; status: string; description: string | null; reported_by: string | null; created_at: string; resolved_at: string | null }; Insert: Partial<Database["public"]["Tables"]["incidents"]["Row"]> & { org_id: string; title: string; severity: string; status: string }; Update: Partial<Database["public"]["Tables"]["incidents"]["Row"]> };
      policies: { Row: { id: string; org_id: string; name: string; version: string | null; content: string | null; status: string; effective_date: string | null; created_at: string; updated_at: string }; Insert: Partial<Database["public"]["Tables"]["policies"]["Row"]> & { org_id: string; name: string; status: string }; Update: Partial<Database["public"]["Tables"]["policies"]["Row"]> };
      training: { Row: { id: string; org_id: string; user_id: string; module: string; status: string; score: number | null; completed_at: string | null; created_at: string }; Insert: Partial<Database["public"]["Tables"]["training"]["Row"]> & { org_id: string; user_id: string; module: string; status: string }; Update: Partial<Database["public"]["Tables"]["training"]["Row"]> };
      datasets: { Row: { id: string; org_id: string; name: string; type: string | null; size_bytes: number | null; status: string; created_at: string }; Insert: Partial<Database["public"]["Tables"]["datasets"]["Row"]> & { org_id: string; name: string; status: string }; Update: Partial<Database["public"]["Tables"]["datasets"]["Row"]> };
      agents: { Row: { id: string; org_id: string; name: string; type: string; status: string; config: Json | null; created_at: string; updated_at: string }; Insert: Partial<Database["public"]["Tables"]["agents"]["Row"]> & { org_id: string; name: string; type: string; status: string }; Update: Partial<Database["public"]["Tables"]["agents"]["Row"]> };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}

export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type TablesInsert<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert'];
export type TablesUpdate<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update'];
