import { useState } from "react";
interface Props { open: boolean; onClose: () => void; }
export default function ModelRegistrationDrawer({ open, onClose }: Props) {
  const [name, setName] = useState("");
  const [version, setVersion] = useState("");
  const [framework, setFramework] = useState("");
  const [status, setStatus] = useState<"idle"|"loading"|"success"|"error">("idle");
  if (!open) return null;
  const handleRegister = async () => { if(!name||!version) return; setStatus("loading"); try { await new Promise(r=>setTimeout(r,1200)); setStatus("success"); } catch { setStatus("error"); } };
  return (<div className="fixed inset-0 z-50 flex justify-end" onClick={onClose}><div className="bg-[hsl(var(--background))] w-[500px] h-full shadow-xl p-6 overflow-auto" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==="Escape")onClose()}} tabIndex={-1}><div className="flex justify-between items-center mb-4"><h2 className="text-xl font-bold">Register Model</h2><button onClick={onClose}>X</button></div><div className="space-y-4"><div><label className="block text-sm font-medium mb-1">Model Name</label><input className="w-full border rounded px-3 py-2" value={name} onChange={e=>setName(e.target.value)}/></div><div><label className="block text-sm font-medium mb-1">Version</label><input className="w-full border rounded px-3 py-2" value={version} onChange={e=>setVersion(e.target.value)}/></div><div><label className="block text-sm font-medium mb-1">Framework</label><select className="w-full border rounded px-3 py-2" value={framework} onChange={e=>setFramework(e.target.value)}><option value="">Select</option><option value="pytorch">PyTorch</option><option value="tensorflow">TensorFlow</option><option value="onnx">ONNX</option></select></div>{status==="success"&&<div className="text-green-600 text-sm">Model registered!</div>}{status==="error"&&<div className="text-red-600 text-sm">Registration failed.</div>}<button className="w-full px-4 py-2 bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))] rounded disabled:opacity-50" disabled={!name||!version||status==="loading"} onClick={handleRegister}>{status==="loading"?"Registering...":"Register"}</button></div></div></div>);}
