// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 CERTIFYI-AI.
//
// Data Subject Requests (`dsar_requests`) — GDPR Arts. 15–22 rights requests
// (access, rectification, erasure, restriction, portability, objection) with
// the statutory one-month response clock.
//
// Two earlier defects are documented here because both were silent:
//
//   * the service wrote `tenant_id`, a column that does not exist on this
//     table (it is scoped by `org_id`), so every save failed at the database
//     while the UI reported success — fixed in the previous pass;
//   * status, request_type and priority were unconstrained free text, so the
//     table accumulated 'in_review' alongside 'In Review' and 'medium'
//     alongside 'normal'. The page filtered on values that never occurred,
//     which is why every stat card read 0 and every row rendered a LOW
//     priority badge. The vocabularies below are now CHECK-constrained in the
//     database; these constants must stay in step with those constraints.
//
// 'overdue' is deliberately not a status. It is derived from due_date at read
// time so it can never go stale against the clock.

import { supabase, isSupabaseConfigured } from '@/lib/supabase'
import { logAction } from '@/lib/auditLogger'

/** Fixed by dsar_requests_request_type_check. */
export const DSR_REQUEST_TYPES = [
  'access', 'rectification', 'erasure', 'restriction', 'portability', 'objection',
] as const
export type DsrRequestType = (typeof DSR_REQUEST_TYPES)[number]

/** Fixed by dsar_requests_status_check. */
export const DSR_STATUSES = [
  'pending', 'in_review', 'in_progress', 'completed', 'rejected',
] as const
export type DsrStatus = (typeof DSR_STATUSES)[number]

/** Fixed by dsar_requests_priority_check. */
export const DSR_PRIORITIES = ['low', 'normal', 'high', 'urgent'] as const
export type DsrPriority = (typeof DSR_PRIORITIES)[number]

export const DSR_TYPE_LABEL: Record<DsrRequestType, string> = {
  access: 'Access', rectification: 'Rectification', erasure: 'Erasure',
  restriction: 'Restriction', portability: 'Portability', objection: 'Objection',
}

export const DSR_STATUS_LABEL: Record<DsrStatus, string> = {
  pending: 'Pending', in_review: 'In review', in_progress: 'In progress',
  completed: 'Completed', rejected: 'Rejected',
}

/** The Article each right is exercised under — shown, never stored as truth. */
export const DSR_TYPE_ARTICLE: Record<DsrRequestType, string> = {
  access: 'GDPR Art. 15', rectification: 'GDPR Art. 16', erasure: 'GDPR Art. 17',
  restriction: 'GDPR Art. 18', portability: 'GDPR Art. 20', objection: 'GDPR Art. 21',
}

/** A request in one of these states no longer runs against the clock. */
const CLOSED: readonly string[] = ['completed', 'rejected']

export interface DsrRequest {
  id: string
  /** Citable reference (DSR-YYYY-NNN). The uuid is never shown. */
  reference?: string
  requesterName: string
  requesterEmail?: string
  requestType: DsrRequestType
  description?: string
  status: DsrStatus
  priority: DsrPriority
  /** Statutory response deadline — one month from receipt under Art. 12(3). */
  dueDate?: string | null
  completedAt?: string | null
  notes?: string
  regulation?: string
  assignee?: string
  submittedDate?: string | null

  // ── Interlinks ────────────────────────────────────────────────────────────
  /** AI systems that hold this subject's data — makes the request actionable. */
  linkedModelIds: string[]
  datasetId?: string | null
  /** The Art. 30 processing activity this request falls under. */
  linkedRopaId?: string | null
  /** The consent record whose lawfulness the request contests, where relevant. */
  linkedConsentId?: string | null
  /** Set when the request was raised by a breach rather than by a subject. */
  incidentId?: string | null
  linkedRiskId?: string | null

  // ── Art. 34 batch communications ──────────────────────────────────────────
  /** True when this row stands for a breach notification to many subjects. */
  isBatch: boolean
  subjectCount?: number | null
  legalBasis?: string

  // ── Provenance ────────────────────────────────────────────────────────────
  source: string
  autoGenerated: boolean
  createdByAgent?: string | null

  /**
   * Days left on the statutory clock, derived from due_date at read time —
   * never stored, so it cannot drift. Null when no deadline is recorded, or
   * when the request is already closed and the clock no longer runs.
   */
  daysRemaining: number | null
  /** Derived, never stored: past the deadline and not yet closed. */
  isOverdue: boolean
  createdAt?: string
  updatedAt?: string
}

function fromRow(r: Record<string, any>): DsrRequest {
  const status = (r.status ?? 'pending') as DsrStatus
  const open = !CLOSED.includes(status)
  const days = r.due_date && open
    ? Math.ceil((new Date(r.due_date).getTime() - Date.now()) / 86_400_000)
    : null
  return {
    id: r.id,
    reference: r.reference ?? undefined,
    requesterName: r.requester_name ?? '',
    requesterEmail: r.requester_email ?? undefined,
    requestType: (r.request_type ?? 'access') as DsrRequestType,
    description: r.description ?? undefined,
    status,
    priority: (r.priority ?? 'normal') as DsrPriority,
    dueDate: r.due_date ?? null,
    completedAt: r.completed_at ?? null,
    notes: r.notes ?? undefined,
    regulation: r.regulation ?? undefined,
    assignee: r.assignee ?? undefined,
    submittedDate: r.submitted_date ?? null,
    linkedModelIds: Array.isArray(r.linked_model_ids) ? r.linked_model_ids : [],
    datasetId: r.dataset_id ?? null,
    linkedRopaId: r.linked_ropa_id ?? null,
    linkedConsentId: r.linked_consent_id ?? null,
    incidentId: r.incident_id ?? null,
    linkedRiskId: r.linked_risk_id ?? null,
    isBatch: !!r.is_batch,
    subjectCount: r.subject_count ?? null,
    legalBasis: r.legal_basis ?? undefined,
    source: r.source ?? 'manual',
    autoGenerated: !!r.auto_generated,
    createdByAgent: r.created_by_agent ?? null,
    daysRemaining: days,
    isOverdue: days != null && days < 0,
    createdAt: r.created_at,
    updatedAt: r.updated_at,
  }
}

/**
 * Project onto real columns. `org_id` is deliberately absent: the DB default
 * (`current_user_org_id()`) fills it, and the client must never choose a
 * tenant. Provenance columns are absent too — only agents set those.
 */
function toRow(d: Partial<DsrRequest>): Record<string, any> {
  const row: Record<string, any> = {}
  if (d.id !== undefined) row.id = d.id
  if (d.reference !== undefined) row.reference = d.reference || null
  if (d.requesterName !== undefined) row.requester_name = d.requesterName
  if (d.requesterEmail !== undefined) row.requester_email = d.requesterEmail || null
  if (d.requestType !== undefined) row.request_type = d.requestType
  if (d.description !== undefined) row.description = d.description || null
  if (d.status !== undefined) row.status = d.status
  if (d.priority !== undefined) row.priority = d.priority
  if (d.dueDate !== undefined) row.due_date = d.dueDate || null
  if (d.completedAt !== undefined) row.completed_at = d.completedAt || null
  if (d.notes !== undefined) row.notes = d.notes || null
  if (d.regulation !== undefined) row.regulation = d.regulation || null
  if (d.assignee !== undefined) row.assignee = d.assignee || null
  if (d.submittedDate !== undefined) row.submitted_date = d.submittedDate || null
  if (d.linkedModelIds !== undefined) row.linked_model_ids = d.linkedModelIds
  if (d.datasetId !== undefined) row.dataset_id = d.datasetId || null
  if (d.linkedRopaId !== undefined) row.linked_ropa_id = d.linkedRopaId || null
  if (d.linkedConsentId !== undefined) row.linked_consent_id = d.linkedConsentId || null
  if (d.incidentId !== undefined) row.incident_id = d.incidentId || null
  if (d.linkedRiskId !== undefined) row.linked_risk_id = d.linkedRiskId || null
  if (d.isBatch !== undefined) row.is_batch = d.isBatch
  if (d.subjectCount !== undefined) row.subject_count = d.subjectCount ?? null
  if (d.legalBasis !== undefined) row.legal_basis = d.legalBasis || null
  return row
}

/**
 * The statutory deadline: one month from receipt (Art. 12(3)). Offered as the
 * default when a request is logged; the operator can still override it, since
 * Art. 12(3) allows a two-month extension for complex requests.
 */
export function statutoryDueDate(from: string | Date = new Date()): string {
  const d = new Date(from)
  d.setMonth(d.getMonth() + 1)
  return d.toISOString().slice(0, 10)
}

export async function fetchAllDsrRequests(filters: Record<string, any> = {}): Promise<DsrRequest[]> {
  if (!isSupabaseConfigured() || !supabase) return []
  let q = supabase.from('dsar_requests').select('*')
    .eq('is_deleted', false)
    .order('created_at', { ascending: false })
  if (filters.status) q = q.eq('status', filters.status)
  if (filters.modelId) q = q.contains('linked_model_ids', [filters.modelId])
  if (filters.ropaId) q = q.eq('linked_ropa_id', filters.ropaId)
  const { data, error } = await q
  if (error) throw new Error(error.message)
  return (data ?? []).map(fromRow)
}

export async function fetchDsrRequest(id: string): Promise<DsrRequest | null> {
  if (!isSupabaseConfigured() || !supabase) return null
  const { data, error } = await supabase.from('dsar_requests').select('*').eq('id', id).single()
  if (error) throw new Error(error.message)
  return data ? fromRow(data) : null
}

export async function upsertDsrRequests(record: Partial<DsrRequest>): Promise<DsrRequest> {
  if (!isSupabaseConfigured() || !supabase) throw new Error('Supabase is not configured — cannot save.')
  const creating = !record.id
  const { data, error } = await supabase
    .from('dsar_requests')
    .upsert({ ...toRow(record), updated_at: new Date().toISOString() })
    .select().single()
  if (error) throw new Error(error.message)
  void logAction({
    module: 'privacy', entityType: 'dsar_requests',
    entityId: String(data.id), action: creating ? 'create' : 'update',
  })
  return fromRow(data)
}

/**
 * Soft delete. A rights request is the evidence that the one-month clock was
 * met; destroying the row destroys the only proof the deadline was honoured,
 * so the record is retained and hidden. (This service previously issued a hard
 * DELETE *and* never filtered is_deleted on read, so soft-deleted rows also
 * stayed visible — the worst of both.)
 */
export async function deleteDsrRequests(id: string): Promise<boolean> {
  if (!isSupabaseConfigured() || !supabase) throw new Error('Supabase is not configured — cannot delete.')
  const { error } = await supabase
    .from('dsar_requests')
    .update({ is_deleted: true, updated_at: new Date().toISOString() })
    .eq('id', id)
  if (error) throw new Error(error.message)
  void logAction({ module: 'privacy', entityType: 'dsar_requests', entityId: id, action: 'delete' })
  return true
}
