// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 CERTIFYI-AI.
//
// Governance facts — the single read-only source of measured platform state.
//
// Narrative Engine and Export Center both need to answer "what is actually
// true right now?". Before this existed, Narrative Engine answered it with a
// hardcoded string containing a fabricated bias violation
// ("Demographic Parity Difference: 0.12 (threshold: 0.10 — VIOLATION)") and a
// model that does not exist in the registry ("MDL-001"), presented as a
// regulator-facing narrative. Export Center answered it with a hardcoded list
// of templates and fake completed jobs.
//
// Every field here is counted from a real table. Nothing is estimated,
// interpolated or defaulted to a flattering value: a count that cannot be read
// comes back as null, and callers must render null as "not measured" rather
// than as 0. The distinction matters — zero open risks and an unreadable risk
// register look identical on a dashboard and mean opposite things.

import { supabase, isSupabaseConfigured } from '@/lib/supabase'

/** A single measured figure, with the query that produced it. */
export interface Fact {
  /** Null means the figure could not be read — never render this as 0. */
  value: number | null
  /** Where it came from, so a reader can verify it. */
  source: string
}

export interface GovernanceFacts {
  measuredAt: string
  models: { total: Fact; highRisk: Fact; production: Fact }
  risks: { total: Fact; open: Fact; critical: Fact; autoGenerated: Fact }
  incidents: { total: Fact; open: Fact }
  privacy: {
    dsarTotal: Fact; dsarOverdue: Fact; dsarOpen: Fact
    consentGranted: Fact; consentWithdrawn: Fact
    ropaActivities: Fact; ropaWithoutSystem: Fact
    dpiaTotal: Fact; dpiaResidualHigh: Fact
    transfersWithoutMechanism: Fact
  }
  controls: { total: Fact; implemented: Fact }
  assets: { total: Fact; linkedToRegistry: Fact }
  useCases: { total: Fact }
  vendors: { total: Fact }
  biasAudits: { total: Fact }
}

const NOT_READ: Fact = { value: null, source: 'not read' }

/** Count rows matching a filter. Returns null (not 0) when the read fails. */
async function count(
  table: string,
  describe: string,
  apply?: (q: any) => any,
): Promise<Fact> {
  if (!isSupabaseConfigured() || !supabase) return NOT_READ
  try {
    let q = supabase.from(table).select('*', { count: 'exact', head: true })
    if (apply) q = apply(q)
    const { count: n, error } = await q
    if (error) return { value: null, source: `${describe} — read failed: ${error.message}` }
    return { value: n ?? 0, source: describe }
  } catch (e: any) {
    return { value: null, source: `${describe} — read failed: ${e?.message ?? 'unknown'}` }
  }
}

/**
 * Read every figure the narrative and export surfaces rely on.
 *
 * Reads run concurrently and independently: one unreadable table degrades that
 * one figure to null rather than failing the whole page, which is what lets the
 * UI say "not measured" for exactly the thing it could not measure.
 */
export async function fetchGovernanceFacts(): Promise<GovernanceFacts> {
  const today = new Date().toISOString().slice(0, 10)

  const [
    modelsTotal, modelsHighRisk, modelsProd,
    risksTotal, risksOpen, risksCritical, risksAuto,
    incidentsTotal, incidentsOpen,
    dsarTotal, dsarOverdue, dsarOpen,
    consentGranted, consentWithdrawn,
    ropaActivities, dpiaTotal, dpiaResidualHigh,
    controlsTotal, controlsImplemented,
    assetsTotal, assetsLinked,
    useCasesTotal, vendorsTotal, biasTotal,
  ] = await Promise.all([
    count('ai_models', 'ai_models'),
    // risk_tier is stored lowercase here, but matching is case-insensitive on
    // purpose: this platform has already shipped one register whose filters
    // silently returned zero because the column had drifted to Title Case.
    count('ai_models', 'ai_models where risk_tier is high/critical/unacceptable',
      (q) => q.or('risk_tier.ilike.high,risk_tier.ilike.critical,risk_tier.ilike.unacceptable')),
    count('ai_models', "ai_models where lifecycle_stage = 'production'",
      (q) => q.eq('lifecycle_stage', 'production')),

    count('risks', 'risks'),
    // mitigation_status is stored Title Case ('Open', 'Mitigating', ...), so a
    // literal 'closed' comparison would match nothing and report every risk as
    // open. Closed states are named explicitly and matched case-insensitively.
    count('risks', 'risks not in a closed/accepted state',
      (q) => q.not('mitigation_status', 'ilike', 'closed')
              .not('mitigation_status', 'ilike', 'accepted')),
    count('risks', 'risks where risk_level is critical',
      (q) => q.ilike('risk_level', 'critical')),
    count('risks', 'risks where auto_generated', (q) => q.eq('auto_generated', true)),

    count('incidents', 'incidents'),
    // incidents close as either 'closed' or 'resolved'; excluding only one
    // would overstate the open count.
    count('incidents', 'incidents not closed or resolved',
      (q) => q.not('status', 'ilike', 'closed').not('status', 'ilike', 'resolved')),

    count('dsar_requests', 'dsar_requests where not deleted', (q) => q.eq('is_deleted', false)),
    count('dsar_requests', 'dsar_requests past due_date and still open',
      (q) => q.eq('is_deleted', false).lt('due_date', today)
              .not('status', 'in', '("completed","rejected")')),
    count('dsar_requests', 'dsar_requests still open',
      (q) => q.eq('is_deleted', false).not('status', 'in', '("completed","rejected")')),

    count('consent_records', "consent_records where status = 'granted'",
      (q) => q.eq('status', 'granted')),
    count('consent_records', "consent_records where status = 'withdrawn'",
      (q) => q.eq('status', 'withdrawn')),

    count('ropa_records', 'ropa_records'),
    count('dpia_assessments', 'dpia_assessments'),
    count('dpia_assessments', 'dpia_assessments with high/critical residual risk',
      (q) => q.or('residual_risk_level.ilike.high,residual_risk_level.ilike.critical')),

    count('controls', 'controls'),
    count('controls', "controls where status is 'implemented'",
      (q) => q.ilike('status', 'implemented')),

    count('assets', 'assets'),
    count('assets', 'assets linked to a registry record', (q) => q.not('entity_id', 'is', null)),

    count('use_cases', 'use_cases'),
    count('vendors', 'vendors', (q) => q.eq('is_deleted', false)),
    count('bias_audits', 'bias_audits'),
  ])

  // Two figures need a shape the count helper cannot express.
  const ropaWithoutSystem = await countRopaWithoutSystem()
  const transfersWithoutMechanism = await count(
    'transfer_impact_assessments',
    'transfer_impact_assessments with no transfer_mechanism',
    (q) => q.is('transfer_mechanism', null),
  )

  return {
    measuredAt: new Date().toISOString(),
    models: { total: modelsTotal, highRisk: modelsHighRisk, production: modelsProd },
    risks: { total: risksTotal, open: risksOpen, critical: risksCritical, autoGenerated: risksAuto },
    incidents: { total: incidentsTotal, open: incidentsOpen },
    privacy: {
      dsarTotal, dsarOverdue, dsarOpen,
      consentGranted, consentWithdrawn,
      ropaActivities, ropaWithoutSystem,
      dpiaTotal, dpiaResidualHigh,
      transfersWithoutMechanism,
    },
    controls: { total: controlsTotal, implemented: controlsImplemented },
    assets: { total: assetsTotal, linkedToRegistry: assetsLinked },
    useCases: { total: useCasesTotal },
    vendors: { total: vendorsTotal },
    biasAudits: { total: biasTotal },
  }
}

/**
 * Art. 30 records naming no AI system. PostgREST cannot express "empty array"
 * as a filter, so the arrays are fetched and counted client-side.
 */
async function countRopaWithoutSystem(): Promise<Fact> {
  if (!isSupabaseConfigured() || !supabase) return NOT_READ
  const describe = 'ropa_records with an empty linked_model_ids'
  try {
    const { data, error } = await supabase.from('ropa_records').select('linked_model_ids')
    if (error) return { value: null, source: `${describe} — read failed: ${error.message}` }
    const n = (data ?? []).filter(
      (r: any) => !Array.isArray(r.linked_model_ids) || r.linked_model_ids.length === 0,
    ).length
    return { value: n, source: describe }
  } catch (e: any) {
    return { value: null, source: `${describe} — read failed: ${e?.message ?? 'unknown'}` }
  }
}

/** Render a Fact for prose: a number, or an explicit "not measured". */
export function say(f: Fact): string {
  return f.value === null ? 'not measured' : String(f.value)
}

/** True when any figure in the set could not be read. */
export function hasUnreadFacts(facts: GovernanceFacts): boolean {
  const walk = (o: any): boolean =>
    Object.values(o).some((v: any) =>
      v && typeof v === 'object'
        ? 'value' in v ? v.value === null : walk(v)
        : false)
  return walk({
    models: facts.models, risks: facts.risks, incidents: facts.incidents,
    privacy: facts.privacy, controls: facts.controls, assets: facts.assets,
    useCases: facts.useCases, vendors: facts.vendors, biasAudits: facts.biasAudits,
  })
}
