// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 CERTIFYI-AI.
//
// Narrative composer — turns measured governance facts into audience-shaped
// prose, with every figure traceable to the query that produced it.
//
// This replaces a hardcoded narrative that stated a bias violation
// ("Demographic Parity Difference: 0.12 (threshold: 0.10 — VIOLATION)") that no
// bias audit had found, against a model code ("MDL-001") that is not in the
// registry. That text was presented as regulator-facing output, which is the
// most consequential place in the platform to invent a number.
//
// Three rules hold here:
//
//   1. Every number comes from a Fact. There are no literals in the prose.
//   2. A figure that could not be read says "not measured" — never 0, and
//      never a plausible-looking substitute.
//   3. The composer describes; it does not conclude. It will say that four
//      DPIAs carry high residual risk; it will not say the organisation is
//      "well controlled". Judgements belong to the human who signs the
//      narrative, which is also what Art. 14 oversight requires.

import type { GovernanceFacts, Fact } from './governanceFactsService'
import { say } from './governanceFactsService'

export const NARRATIVE_AUDIENCES = ['board', 'regulator', 'technical'] as const
export type NarrativeAudience = (typeof NARRATIVE_AUDIENCES)[number]

export const AUDIENCE_LABEL: Record<NarrativeAudience, string> = {
  board: 'Board of Directors',
  regulator: 'Supervisory Authority',
  technical: 'Engineering & Risk',
}

export interface ComposedNarrative {
  title: string
  body: string
  /** Every figure used, so the reader can check the source of each one. */
  citations: { label: string; value: string; source: string }[]
  /** True when at least one figure could not be read from the database. */
  incomplete: boolean
  wordCount: number
}

function cite(label: string, f: Fact) {
  return { label, value: say(f), source: f.source }
}

/** Plural-safe noun phrase: "1 model" / "3 models" / "not measured models". */
function n(f: Fact, singular: string, plural = `${singular}s`): string {
  if (f.value === null) return `an unmeasured number of ${plural}`
  return `${f.value} ${f.value === 1 ? singular : plural}`
}

export function composeNarrative(
  audience: NarrativeAudience,
  facts: GovernanceFacts,
  orgName: string,
): ComposedNarrative {
  const measured = new Date(facts.measuredAt).toISOString().slice(0, 10)
  const p = facts.privacy

  const citations = [
    cite('AI systems registered', facts.models.total),
    cite('High-risk AI systems', facts.models.highRisk),
    cite('Open risks', facts.risks.open),
    cite('Critical risks', facts.risks.critical),
    cite('Risks raised automatically', facts.risks.autoGenerated),
    cite('Open incidents', facts.incidents.open),
    cite('Rights requests open', p.dsarOpen),
    cite('Rights requests overdue', p.dsarOverdue),
    cite('Art. 30 processing activities', p.ropaActivities),
    cite('Art. 30 records naming no system', p.ropaWithoutSystem),
    cite('DPIAs', p.dpiaTotal),
    cite('DPIAs at high/critical residual risk', p.dpiaResidualHigh),
    cite('Transfers with no Chapter V mechanism', p.transfersWithoutMechanism),
    cite('Controls', facts.controls.total),
    cite('Controls implemented', facts.controls.implemented),
    cite('Assets', facts.assets.total),
    cite('Assets linked to a registry record', facts.assets.linkedToRegistry),
  ]

  const incomplete = citations.some((c) => c.value === 'not measured')
  const caveat = incomplete
    ? '\n\nFigures marked "not measured" could not be read from the governance ' +
      'database at the time of generation. They are not zero; they are unknown, ' +
      'and this narrative must not be submitted until they are resolved.'
    : ''

  let title: string
  let body: string

  if (audience === 'board') {
    title = `${orgName} — AI risk position as at ${measured}`
    body =
`This summary is generated from the governance registers and reflects their state on ${measured}. Every figure is drawn from a record; none is estimated.

PORTFOLIO. ${orgName} has ${n(facts.models.total, 'AI system')} on the register, of which ${say(facts.models.highRisk)} are classified high-risk and ${say(facts.models.production)} are in production. ${n(facts.useCases.total, 'business use case')} are recorded against them.

RISK. ${n(facts.risks.open, 'risk')} are open, ${say(facts.risks.critical)} of them rated critical. ${say(facts.risks.autoGenerated)} were raised automatically by the governance agents rather than by a person, which is a measure of how much of the register is machine-detected rather than a judgement about severity. ${n(facts.incidents.open, 'incident')} remain open.

OBLIGATIONS. ${n(p.dsarOpen, 'data subject rights request')} are open, ${say(p.dsarOverdue)} of them past the one-month statutory deadline. ${n(p.dpiaResidualHigh, 'data protection impact assessment')} closed with high or critical residual risk. ${n(p.transfersWithoutMechanism, 'cross-border transfer')} are recorded with no Chapter V transfer mechanism.

CONTROL COVERAGE. ${say(facts.controls.implemented)} of ${say(facts.controls.total)} controls are marked implemented. ${say(facts.assets.linkedToRegistry)} of ${say(facts.assets.total)} assets resolve to a model or dataset in the registry; the remainder are infrastructure or unlinked.

This document states position, not assurance. Whether the position is acceptable is a judgement for the Board, and this narrative deliberately does not make it.${caveat}`
  } else if (audience === 'regulator') {
    title = `${orgName} — governance record extract as at ${measured}`
    body =
`Prepared from ${orgName}'s governance registers on ${measured}. Figures are counts of records held, not assertions of compliance.

ART. 30 REGISTER. ${n(p.ropaActivities, 'processing activity')} are recorded. ${say(p.ropaWithoutSystem)} of them name no AI system in the register; where that is so, the controller cannot yet evidence which system carries out the processing and this is stated rather than omitted.

ARTS. 15–22 RIGHTS. ${n(p.dsarTotal, 'rights request')} are held, ${say(p.dsarOpen)} open and ${say(p.dsarOverdue)} past the Art. 12(3) one-month deadline. Deadlines are derived from the recorded receipt date at read time, not stored, so they cannot go stale.

ART. 7 CONSENT. ${say(p.consentGranted)} consents are recorded as granted and ${say(p.consentWithdrawn)} as withdrawn.

ARTS. 35–36 DPIA. ${n(p.dpiaTotal, 'assessment')} are held; ${say(p.dpiaResidualHigh)} record high or critical residual risk, the condition that engages Art. 36 prior consultation.

CHAPTER V TRANSFERS. ${n(p.transfersWithoutMechanism, 'transfer')} are recorded with no adequacy decision, standard contractual clauses, binding corporate rules or Art. 49 derogation identified.

AI SYSTEMS. ${n(facts.models.total, 'system')} registered, ${say(facts.models.highRisk)} classified high-risk. ${n(facts.biasAudits.total, 'bias audit')} are on file.

${orgName} makes no claim of completeness in this extract beyond the records described. Any figure shown as "not measured" was unreadable at generation time and is not a nil return.${caveat}`
  } else {
    title = `${orgName} — engineering risk briefing, ${measured}`
    body =
`Generated from the registers on ${measured}.

SYSTEMS. ${say(facts.models.total)} registered, ${say(facts.models.production)} in production, ${say(facts.models.highRisk)} high-risk. ${say(facts.assets.linkedToRegistry)} of ${say(facts.assets.total)} asset records resolve to a model or dataset — unlinked assets cannot participate in impact analysis.

RISK REGISTER. ${say(facts.risks.open)} open of ${say(facts.risks.total)} total; ${say(facts.risks.critical)} critical. ${say(facts.risks.autoGenerated)} were opened by agents. Agent-raised risks are never auto-closed: closing one is a human action under Art. 14 oversight.

INCIDENTS. ${say(facts.incidents.open)} open of ${say(facts.incidents.total)}.

PRIVACY ENGINEERING. ${say(p.dsarOverdue)} rights requests past deadline. ${say(p.ropaWithoutSystem)} Art. 30 records name no system, which is the interlink gap that blocks erasure from being actionable. ${say(p.transfersWithoutMechanism)} transfers carry no Chapter V mechanism.

CONTROLS. ${say(facts.controls.implemented)} of ${say(facts.controls.total)} implemented. ${say(facts.vendors.total)} vendors on the register.${caveat}`
  }

  return {
    title,
    body,
    citations,
    incomplete,
    wordCount: body.trim().split(/\s+/).length,
  }
}
