# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 CERTIFYI-AI.
"""Capsule CRM integration adapter.

Reads user/admin roster, webhook subscriptions, and account posture from
the Capsule CRM API for access-review and data-location evidence: admin
account hygiene, SSO/MFA enforcement (where exposed), and outbound
webhook endpoint exposure.

Auth: a single api_key (Bearer token issued from Capsule > My Preferences
> API Authentication Tokens).
"""

from __future__ import annotations

import asyncio
import logging
from dataclasses import dataclass
from urllib.parse import urlparse

import httpx

from sentinel.integrations.base import IntegrationFinding

logger = logging.getLogger(__name__)

_TIMEOUT = httpx.Timeout(30.0, connect=10.0)
_BASE = "https://api.capsulecrm.com/api/v2"


@dataclass
class CapsuleCredentials:
    """Matches dashboard/src/integrations/capsule/config.ts credentialFields."""

    api_key: str


class CapsuleAdapter:
    """Fetches user roster and access posture from Capsule CRM."""

    def __init__(self, credentials: CapsuleCredentials, client: httpx.AsyncClient | None = None) -> None:
        self.credentials = credentials
        self._client = client

    def _headers(self) -> dict[str, str]:
        return {
            "Authorization": f"Bearer {self.credentials.api_key}",
            "Accept": "application/json",
        }

    async def _open(self) -> httpx.AsyncClient:
        if self._client is not None:
            return self._client
        return httpx.AsyncClient(timeout=_TIMEOUT)

    async def _get(self, client: httpx.AsyncClient, path: str, **params) -> httpx.Response:
        return await client.get(
            f"{_BASE}{path}",
            headers=self._headers(),
            params=params or None,
            timeout=_TIMEOUT,
        )

    async def validate(self) -> bool:
        """One lightweight authenticated call; ValueError on bad credentials."""
        client = await self._open()
        try:
            resp = await self._get(client, "/users/current")
            if resp.status_code in (401, 403):
                raise ValueError(
                    "Capsule rejected the API key. Verify the key is active "
                    "and was generated by a user with API access."
                )
            resp.raise_for_status()
            return True
        except ValueError:
            raise
        except Exception as exc:
            raise ValueError(f"Could not reach Capsule CRM: {exc}") from exc
        finally:
            if self._client is None:
                await client.aclose()

    async def fetch_all(self) -> list[IntegrationFinding]:
        """Run every check; one check failing never sinks the sync."""
        client = await self._open()
        try:
            results = await asyncio.gather(
                self._check_admin_hygiene(client),
                self._check_sso_enforcement(client),
                self._check_webhook_exposure(client),
                return_exceptions=True,
            )
        finally:
            if self._client is None:
                await client.aclose()

        findings: list[IntegrationFinding] = []
        for result in results:
            if isinstance(result, BaseException):
                logger.warning("capsule check failed: %s", result)
                continue
            findings.extend(result)
        return findings

    # -- checks ----------------------------------------------------------------

    async def _check_admin_hygiene(self, client: httpx.AsyncClient) -> list[IntegrationFinding]:
        resp = await self._get(client, "/users", perPage=100)
        if resp.status_code in (403, 404):
            return [self._unavailable(
                "capsule.users.admin_hygiene",
                "Administrator account hygiene",
                "least_privilege",
                "Grant the API key read access to the Users resource.",
            )]
        resp.raise_for_status()
        data = resp.json()
        users = data.get("users", data if isinstance(data, list) else [])
        admins = [u for u in users if u.get("administrator")]
        inactive_admins = [u for u in admins if u.get("active") is False]
        total = len(users)
        passed = not inactive_admins and (total == 0 or len(admins) / total <= 0.5)
        return [IntegrationFinding(
            check_id="capsule.users.admin_hygiene",
            title="Administrator accounts are reviewed and active-only",
            description=(
                f"{len(admins)} of {total} user(s) hold administrator rights; "
                f"{len(inactive_admins)} inactive administrator account(s) found."
            ),
            remediation=(
                "Remove administrator rights from inactive or unused accounts "
                "and keep the administrator group limited to those who need it."
            ),
            status="PASSED" if passed else ("FAILED" if inactive_admins else "WARNING"),
            severity="HIGH" if inactive_admins else ("MEDIUM" if not passed else "INFO"),
            check_category="least_privilege",
            result_details={
                "total_users": total,
                "administrator_count": len(admins),
                "inactive_administrator_count": len(inactive_admins),
            },
        )]

    async def _check_sso_enforcement(self, client: httpx.AsyncClient) -> list[IntegrationFinding]:
        # Capsule's REST API has no documented endpoint for org-wide SSO/MFA
        # enforcement policy — it is only configurable in the web console.
        # We still make the call so a future API addition is picked up
        # automatically instead of silently staying unavailable forever.
        resp = await self._get(client, "/users/current")
        if resp.status_code >= 400:
            return [self._unavailable(
                "capsule.security.sso_enforcement",
                "SSO/MFA enforcement",
                "mfa_enforcement",
                "Capsule did not return account security settings for this key.",
            )]
        data = resp.json().get("user", {})
        if "twoFactorEnabled" not in data and "ssoEnabled" not in data:
            return [self._unavailable(
                "capsule.security.sso_enforcement",
                "SSO/MFA enforcement",
                "mfa_enforcement",
                "Capsule's API does not expose organization-wide SSO/MFA "
                "enforcement status. Verify manually in Account Settings > "
                "Security.",
            )]
        enabled = bool(data.get("twoFactorEnabled") or data.get("ssoEnabled"))
        return [IntegrationFinding(
            check_id="capsule.security.sso_enforcement",
            title="SSO/MFA is enforced for the account",
            description="Two-factor/SSO enforcement flag reported by Capsule for this token's account.",
            remediation="Enable and enforce two-factor authentication or SSO for all Capsule users.",
            status="PASSED" if enabled else "FAILED",
            severity="INFO" if enabled else "HIGH",
            check_category="mfa_enforcement",
            result_details={"reported_enabled": enabled},
        )]

    async def _check_webhook_exposure(self, client: httpx.AsyncClient) -> list[IntegrationFinding]:
        resp = await self._get(client, "/webhooks", perPage=100)
        if resp.status_code in (403, 404):
            return [self._unavailable(
                "capsule.webhooks.insecure_endpoints",
                "Outbound webhook endpoint exposure",
                "data_classification",
                "Grant the API key read access to the Webhooks resource.",
            )]
        resp.raise_for_status()
        data = resp.json()
        hooks = data.get("webhooks", data if isinstance(data, list) else [])
        insecure = []
        for hook in hooks:
            target = hook.get("restHookUrl") or hook.get("targetUrl") or ""
            if target and urlparse(target).scheme != "https":
                insecure.append(target)
        return [IntegrationFinding(
            check_id="capsule.webhooks.insecure_endpoints",
            title="Webhook subscriptions deliver CRM data only over HTTPS",
            description=(
                f"{len(insecure)} of {len(hooks)} webhook subscription(s) deliver "
                "party/case data to a non-HTTPS endpoint."
            ),
            remediation=(
                "Reconfigure or remove webhook subscriptions that point at "
                "non-HTTPS endpoints — CRM data is exposed in transit otherwise."
            ),
            status="PASSED" if not insecure else "FAILED",
            severity="HIGH" if insecure else "INFO",
            check_category="data_classification",
            result_details={
                "webhook_count": len(hooks),
                "insecure_endpoint_count": len(insecure),
            },
        )]

    @staticmethod
    def _unavailable(check_id: str, title: str, category: str, remediation: str) -> IntegrationFinding:
        return IntegrationFinding(
            check_id=check_id, title=title,
            description="Sentinel could not read this from Capsule CRM with the supplied credentials.",
            remediation=remediation,
            status="NOT_AVAILABLE", severity="INFO",
            check_category=category, result_details={},
        )
