import {NavLink} from 'react-router-dom';
import {useTheme} from '../context/ThemeContext';
import {LayoutDashboard,ShieldCheck,ListChecks,AlertTriangle,FileText,Database,BookOpen,Scale,FlaskConical,GitBranch,Activity,Network,Package,BarChart3,Wrench,Download,Bell,Settings,Target,TrendingUp,CheckSquare,Layers,Globe,Sun,Moon,Archive,Shield,Radio,Crosshair,Bug,KeyRound,MapPin} from 'lucide-react';
const NAV=[{s:'OVERVIEW',i:[{l:'Dashboard',icon:LayoutDashboard,to:'/overview'}]},{s:'TRUST & SAFETY',i:[{l:'Audit Log',icon:ListChecks,to:'/audit-log'},{l:'HITL Queue',icon:ShieldCheck,to:'/hitl-queue'},{l:'Incident Log',icon:AlertTriangle,to:'/incident-log'}]},{s:'COMPLIANCE',i:[{l:'Compliance',icon:Scale,to:'/compliance'},{l:'Evidence Vault',icon:Database,to:'/evidence'},{l:'Policy Editor',icon:FileText,to:'/policy-editor'},{l:'Gap Analysis',icon:Target,to:'/gap-analysis'}]},{s:'RISK & MODELS',i:[{l:'Model Inventory',icon:Package,to:'/models'},{l:'Model Lifecycle',icon:GitBranch,to:'/model-lifecycle'},{l:'Risk Matrix',icon:Layers,to:'/risk-matrix'},{l:'Vendor Register',icon:Globe,to:'/vendors'},{l:'Benchmark',icon:BarChart3,to:'/benchmark'}]},{s:'EVAL WORKBENCH',i:[{l:'Eval Runs',icon:FlaskConical,to:'/evals'},{l:'Metric Studio',icon:TrendingUp,to:'/metric-studio'},{l:'Dataset Hub',icon:Archive,to:'/datasets'},{l:'Multi-Turn Editor',icon:BookOpen,to:'/multiturn'}]},{s:'PROXY MONITOR',i:[{l:'Activity Timeline',icon:Activity,to:'/proxy'},{l:'Dependency Graph',icon:Network,to:'/dependency-graph'}]},{s:'SECURITY INTELLIGENCE',i:[{l:'Security Overview',icon:Shield,to:'/security'},{l:'Threat Feed',icon:Radio,to:'/security/threat-feed'},{l:'Scan Center',icon:Crosshair,to:'/security/scan-center'},{l:'Attack Surface',icon:MapPin,to:'/security/attack-surface'},{l:'Red Team Lab',icon:FlaskConical,to:'/security/red-team'},{l:'Policy Firewall',icon:ShieldCheck,to:'/security/policy-firewall'},{l:'Vuln Tracker',icon:Bug,to:'/security/vuln-tracker'},{l:'Keys Vault',icon:KeyRound,to:'/security/keys-vault'}]},{s:'OPERATIONS',i:[{l:'Task Board',icon:CheckSquare,to:'/tasks'},{l:'Remediation',icon:Wrench,to:'/remediation'},{l:'Export Center',icon:Download,to:'/export'},{l:'Notifications',icon:Bell,to:'/notifications'}]},{s:'SETTINGS',i:[{l:'Settings',icon:Settings,to:'/settings'}]}];
export default function Sidebar(){
  const{theme,toggle}=useTheme();
  const b='flex items-center gap-2.5 px-3 py-2 rounded-lg text-sm font-medium transition-all';
  const a='bg-blue-600 text-white shadow-sm';const n='text-slate-600 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800';
  return(<aside className="w-56 flex-shrink-0 h-screen overflow-y-auto flex flex-col bg-white dark:bg-slate-900 border-r border-slate-200 dark:border-slate-700">
    <div className="flex items-center justify-between px-4 py-4 border-b border-slate-200 dark:border-slate-700">
      <div className="flex items-center gap-2"><div className="w-8 h-8 bg-blue-600 rounded-xl flex items-center justify-center"><ShieldCheck size={16} className="text-white"/></div><div><div className="font-bold text-slate-900 dark:text-white text-sm">Sentinel</div><div className="text-[10px] text-slate-400">AI Compliance</div></div></div>
      <button onClick={toggle} className="p-1.5 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-500">{theme==='dark'?<Sun size={14}/>:<Moon size={14}/>}</button>
    </div>
    <nav className="flex-1 px-2 py-3 space-y-4 overflow-y-auto">{NAV.map(({s,i})=>(<div key={s}><p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest px-3 mb-1">{s}</p><ul className="space-y-0.5">{i.map(({l,icon:Icon,to})=>(<li key={to}><NavLink to={to} className={({isActive})=>`${b} ${isActive?a:n}`}><Icon size={14} className="flex-shrink-0"/><span className="truncate">{l}</span></NavLink></li>))}</ul></div>))}</nav>
    <div className="p-3 border-t border-slate-200 dark:border-slate-700"><div className="flex items-center gap-2 px-2 py-2"><div className="w-7 h-7 rounded-full bg-gradient-to-br from-blue-400 to-blue-600 flex items-center justify-center"><span className="text-white text-xs font-bold">A</span></div><div><p className="text-xs font-semibold text-slate-900 dark:text-white">Admin</p><p className="text-[10px] text-slate-400">certifyi.ai</p></div></div></div>
  </aside>);
}
