/**
 * Risk Assessment Agent
 * Triggered by: MODEL_REGISTERED
 * Action: auto-creates risk entry in risk store
 */
import { emitEvent } from '../lib/governance/eventBus'

export async function riskAssessmentAgent(
  payload: Record<string, unknown>,
  orgId: string
) {
  const { modelId, modelName, riskTier, vendor } = payload as any
  const riskId = `RSK-AUTO-${Date.now()}`
  const likelihood = (riskTier as number) <= 2 ? 4 : 2
  const impact = (riskTier as number) <= 2 ? 4 : 2

  console.log(`[RiskAssessmentAgent] Auto-creating risk for model: ${modelName}`)

  // Emit downstream event for other agents to pick up
  await emitEvent('RISK_CREATED', 'risk-agent', {
    riskId,
    modelId,
    modelName,
    severity: impact,
    autoGenerated: true,
    title: `Automated Risk: ${modelName} - Initial Assessment`,
    likelihood,
    impact,
  }, orgId)
}
