/**
 * RiskAssessmentAgent
 * Trigger: MODEL_REGISTERED
 * Action:  Creates a Risk Register entry, emits RISK_CREATED.
 */
import type { AgentContext, AgentResult } from '../lib/governance/types/events'
import type { ModelRegisteredPayload } from '../lib/governance/types/events'
import { calculateInitialRiskScore, safeInsert } from '../lib/governance/agentHelpers'

export async function riskAssessmentAgent(ctx: AgentContext): Promise<AgentResult> {
  const p = ctx.event.payload as unknown as ModelRegisteredPayload
  if (!p?.modelId) return { status: 'skipped', error: 'no-modelId' }

  const score = calculateInitialRiskScore({
    modelType:       p.modelType ?? 'OTHER',
    dataSensitivity: p.dataSensitivity ?? 'PUBLIC',
    deploymentScope: p.deploymentScope ?? 'DEV',
    vendor:          p.vendor,
    euAiActClass:    p.euAiActClass,
  })

  // risks.severity is INTEGER 1–5 and rows are read through the tenant-scoped
  // RLS policy, so tenant_id must follow the org explicitly in agent context.
  const SEV_INT: Record<string, number> = { CRITICAL: 5, HIGH: 4, MEDIUM: 3, LOW: 2 }
  const risk = await safeInsert<{ id: string }>('risks', {
    org_id:      ctx.orgId,
    tenant_id:   ctx.orgId,
    title:       `Auto: ${p.modelName ?? p.modelId} — Initial AI Model Risk`,
    name:        `Auto: ${p.modelName ?? p.modelId} — Initial AI Model Risk`,
    category:    'AI Model Risk',
    description: `Auto-generated from MODEL_REGISTERED. Vendor=${p.vendor ?? 'internal'}, Tier=${p.riskTier}, Purpose=${p.purpose}.`,
    likelihood:  score.likelihood,
    impact:      score.impact,
    severity:    SEV_INT[score.severity] ?? 3,
    status:      'open',
    owner_id:    p.ownerId,
    source:      'auto-agent',
    linked_model_ids: [p.modelId],
    metadata:    { modelId: p.modelId, modelName: p.modelName, createdBy: 'RiskAssessmentAgent' },
  })

  await ctx.emit('RISK_CREATED', 'risk-register', {
    riskId:      risk?.id,
    modelId:     p.modelId,
    modelName:   p.modelName,
    severity:    score.severity,
    likelihood:  score.likelihood,
    impact:      score.impact,
    autoGenerated: true,
  })

  ctx.log(`Created risk ${risk?.id ?? 'local'} severity=${score.severity}`)
  return { status: 'succeeded', output: { riskId: risk?.id, severity: score.severity } }
}
