import { Warning, Plus, MagnifyingGlass } from '@phosphor-icons/react';
import { useState, useMemo } from "react";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '../../components/ui/table';
interface Risk { id: string; title: string; category: string; likelihood: "high"|"medium"|"low"; impact: "high"|"medium"|"low"; owner: string; status: "open"|"mitigated"|"accepted"; }
export default function RiskRegister() {
  const [search, setSearch] = useState("");
  const risks = useMemo<Risk[]>(() => [{id:"1",title:"Model bias in hiring",category:"Fairness",likelihood:"high",impact:"high",owner:"Alice",status:"open"},{id:"2",title:"Data privacy breach",category:"Privacy",likelihood:"medium",impact:"high",owner:"Bob",status:"open"},{id:"3",title:"Model hallucination",category:"Reliability",likelihood:"high",impact:"medium",owner:"Carol",status:"mitigated"},{id:"4",title:"Vendor lock-in",category:"Strategic",likelihood:"low",impact:"medium",owner:"Dave",status:"accepted"}],[]);
  const filtered = risks.filter(r=>r.title.toLowerCase().includes(search.toLowerCase()));
  const levelColors = {high:"bg-red-100 text-red-800",medium:"bg-yellow-100 text-yellow-800",low:"bg-green-100 text-green-800"};
  return (<div className="p-6"><h1 className="text-2xl font-bold mb-1">Risk Register</h1><p className="text-sm text-muted-foreground mb-4">Track and manage AI risks</p><div className="flex gap-2 mb-4"><input placeholder="Search risks..." className="border rounded px-3 py-2 flex-1" value={search} onChange={e=>setSearch(e.target.value)}/><button className="px-4 py-2 bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))] rounded">Add Risk</button></div>{filtered.length===0?(<div className="text-center py-12 text-muted-foreground">No risks found.</div>):(<Table className="w-full border-collapse text-foreground"><TableHeader><TableRow className="border-b"><TableHead className="text-left p-2">Risk</TableHead><TableHead className="text-left p-2">Category</TableHead><TableHead className="text-left p-2">Likelihood</TableHead><TableHead className="text-left p-2">Impact</TableHead><TableHead className="text-left p-2">Owner</TableHead><TableHead className="text-left p-2">Status</TableHead></TableRow></TableHeader><TableBody>{filtered.map(r=>(<TableRow key={r.id} className="border-b hover:bg-[hsl(var(--muted))]"><TableCell className="p-2">{r.title}</TableCell><TableCell className="p-2">{r.category}</TableCell><TableCell className="p-2"><span className={`px-2 py-0.5 rounded text-xs ${levelColors[r.likelihood]}`}>{r.likelihood}</span></TableCell><TableCell className="p-2"><span className={`px-2 py-0.5 rounded text-xs ${levelColors[r.impact]}`}>{r.impact}</span></TableCell><TableCell className="p-2">{r.owner}</TableCell><TableCell className="p-2">{r.status}</TableCell></TableRow>))}</TableBody></Table>)}</div>);}
