import { Buildings, Plus, MagnifyingGlass, Warning } from '@phosphor-icons/react';
import { useState, useMemo } from "react";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '../../components/ui/table';
interface Vendor { id: string; name: string; service: string; riskLevel: "high"|"medium"|"low"; lastAudit: string; status: "active"|"inactive"|"review"; }
export default function VendorRegister() {
  const [search, setSearch] = useState("");
  const vendors = useMemo<Vendor[]>(() => [{id:"1",name:"OpenAI",service:"LLM API",riskLevel:"high",lastAudit:"2024-01-10",status:"active"},{id:"2",name:"Anthropic",service:"LLM API",riskLevel:"medium",lastAudit:"2024-01-08",status:"active"},{id:"3",name:"AWS",service:"Cloud Infra",riskLevel:"low",lastAudit:"2024-01-05",status:"active"},{id:"4",name:"Hugging Face",service:"Model Hub",riskLevel:"medium",lastAudit:"2023-12-15",status:"review"}],[]);
  const filtered = vendors.filter(v=>v.name.toLowerCase().includes(search.toLowerCase()));
  const riskColors = {high:"bg-red-100 text-red-800",medium:"bg-yellow-100 text-yellow-800",low:"bg-green-100 text-green-800"};
  return (<div className="p-6"><h1 className="text-2xl font-bold mb-1">Vendor Register</h1><p className="text-sm text-muted-foreground mb-4">Manage AI vendor relationships</p><div className="flex gap-2 mb-4"><input placeholder="Search vendors..." className="border rounded px-3 py-2 flex-1" value={search} onChange={e=>setSearch(e.target.value)}/><button className="px-4 py-2 bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))] rounded">Add Vendor</button></div>{filtered.length===0?(<div className="text-center py-12 text-muted-foreground">No vendors found.</div>):(<Table className="w-full border-collapse text-foreground"><TableHeader><TableRow className="border-b"><TableHead className="text-left p-2">Vendor</TableHead><TableHead className="text-left p-2">Service</TableHead><TableHead className="text-left p-2">Risk</TableHead><TableHead className="text-left p-2">Last Audit</TableHead><TableHead className="text-left p-2">Status</TableHead></TableRow></TableHeader><TableBody>{filtered.map(v=>(<TableRow key={v.id} className="border-b hover:bg-[hsl(var(--muted))]"><TableCell className="p-2">{v.name}</TableCell><TableCell className="p-2">{v.service}</TableCell><TableCell className="p-2"><span className={`px-2 py-0.5 rounded text-xs ${riskColors[v.riskLevel]}`}>{v.riskLevel}</span></TableCell><TableCell className="p-2">{v.lastAudit}</TableCell><TableCell className="p-2">{v.status}</TableCell></TableRow>))}</TableBody></Table>)}</div>);}
