import React from 'react';
import { cn } from '../../lib/utils';
export const Table=React.forwardRef<HTMLTableElement,React.HTMLAttributes<HTMLTableElement>>(({className,...p},r)=>(<div className="relative w-full overflow-auto"><table ref={r} className={cn("w-full caption-bottom text-sm",className)} {...p}/></div>));
Table.displayName="Table";
export const TableHeader=React.forwardRef<HTMLTableSectionElement,React.HTMLAttributes<HTMLTableSectionElement>>(({className,...p},r)=>(<thead ref={r} className={cn("border-b border-border",className)} {...p}/>));
TableHeader.displayName="TableHeader";
export const TableBody=React.forwardRef<HTMLTableSectionElement,React.HTMLAttributes<HTMLTableSectionElement>>(({className,...p},r)=>(<tbody ref={r} className={cn("divide-y divide-border",className)} {...p}/>));
TableBody.displayName="TableBody";
export const TableRow=React.forwardRef<HTMLTableRowElement,React.HTMLAttributes<HTMLTableRowElement>>(({className,...p},r)=>(<tr ref={r} className={cn("hover:bg-muted/30 transition-colors",className)} {...p}/>));
TableRow.displayName="TableRow";
export const TableHead=React.forwardRef<HTMLTableCellElement,React.ThHTMLAttributes<HTMLTableCellElement>>(({className,...p},r)=>(<th ref={r} className={cn("h-10 px-4 text-left align-middle font-semibold text-foreground",className)} {...p}/>));
TableHead.displayName="TableHead";
export const TableCell=React.forwardRef<HTMLTableCellElement,React.TdHTMLAttributes<HTMLTableCellElement>>(({className,...p},r)=>(<td ref={r} className={cn("px-4 py-2.5 align-middle text-foreground",className)} {...p}/>));
TableCell.displayName="TableCell";
