#!/bin/bash
set -euo pipefail

git filter-branch --force --msg-filter '
  sed \
    -e "s/\[Claude\]//gi" \
    -e "s/\[Replit\]//gi" \
    -e "s/\[AI\]//gi" \
    -e "s/\[AI Agent\]//gi" \
    -e "s/AI-generated://gi" \
    -e "s/Generated by Claude//gi" \
    -e "s/Generated by Replit//gi" \
    -e "s/Co-authored-by: Claude.*//gi" \
    -e "s/Co-authored-by: Replit.*//gi" \
    -e "/^$/d" \
    -e "s/^[[:space:]]*//" \
    -e "s/[[:space:]]*$//"
' --tag-name-filter cat -- --branches --tags

git for-each-ref --format="%(refname)" refs/original/ | \
  xargs -I{} git update-ref -d {}

git reflog expire --expire=now --all
git gc --prune=now --aggressive

echo "History scrubbed. Force push with: git push --force-with-lease origin main"
