#!/bin/bash
set -euo pipefail

# Remove AI comment headers from TS/TSX files
find dashboard/src -type f \( -name "*.ts" -o -name "*.tsx" \) -exec sed -i \
  -e '/\/\/ Generated by Claude/d' \
  -e '/\/\/ Generated by Replit/d' \
  -e '/\/\/ AI-generated/d' \
  -e '/\/\/ @ai-generated/d' \
  -e '/\/\*.*AI.*generated.*\*\//d' \
  -e '/\/\*.*Generated.*Claude.*\*\//d' \
  -e '/\/\*.*Generated.*Replit.*\*\//d' \
  -e '/\/\/ This file was.*generated/d' \
  -e '/\/\/ DO NOT EDIT.*generated/d' \
  -e '/Powered by Claude/d' \
  {} \;

# Remove from docs
find docs -type f -name "*.md" -exec sed -i \
  -e 's/Powered by Claude//g' \
  -e 's/Generated by Claude//g' \
  -e 's/Generated by Replit//g' \
  -e 's/AI-generated documentation//g' \
  {} \;

echo "Source scrub complete."
