INSERT INTO controls (framework_id, control_ref, name, description, severity)
SELECT f.id, v.ref, v.name, v.desc, v.sev FROM frameworks f,
(VALUES
('SAIF 1.1','Secure AI Development Lifecycle','Implement security throughout AI development lifecycle.','Medium'),
('SAIF 1.2','AI Model Security Assessment','Assess security of AI models regularly.','Medium'),
('SAIF 2.1','Training Data Security','Secure AI training data from unauthorized access.','Medium'),
('SAIF 2.2','Model Poisoning Prevention','Prevent poisoning of AI models through data or training.','Medium'),
('SAIF 2.3','Adversarial Robustness Testing','Test AI systems against adversarial attacks.','Medium'),
('SAIF 3.1','AI Supply Chain Security','Secure the AI model and component supply chain.','Medium'),
('SAIF 3.2','Model Integrity Verification','Verify integrity of AI models in production.','Medium'),
('SAIF 4.1','Inference Security Controls','Secure AI inference endpoints and pipelines.','Medium'),
('SAIF 4.2','API Security for AI','Implement security controls for AI APIs.','Medium'),
('SAIF 4.3','AI Access Control','Implement authentication and access control for AI.','Medium'),
('SAIF 5.1','AI Monitoring & Detection','Monitor AI systems for security anomalies.','Medium'),
('SAIF 5.2','AI Incident Response','Establish incident response procedures for AI security.','Medium'),
('SAIF 5.3','Red Team Testing for AI','Conduct red team exercises targeting AI systems.','Medium'),
('SAIF 6.1','Model Extraction Prevention','Prevent unauthorized extraction of AI models.','Medium'),
('SAIF 6.2','Data Exfiltration Prevention','Prevent data exfiltration through AI systems.','Medium'),
('SAIF 7.1','Privacy-Preserving AI','Implement privacy-preserving techniques in AI.','Medium'),
('SAIF 7.2','Federated Learning Security','Secure federated learning implementations.','Medium'),
('SAIF 8.1','AI Vulnerability Management','Manage vulnerabilities in AI systems.','Medium'),
('SAIF 8.2','Patch Management for AI','Implement patch management for AI components.','Medium'),
('SAIF 9.1','Secure Model Deployment','Deploy AI models securely to production.','Medium'),
('SAIF 9.2','Container Security for AI','Secure containers running AI workloads.','Medium'),
('SAIF 10.1','AI Network Security','Implement network security for AI infrastructure.','Medium'),
('SAIF 10.2','Encryption for AI Data','Encrypt AI data at rest and in transit.','Medium'),
('SAIF 11.1','AI Audit Logging','Maintain comprehensive audit logs for AI systems.','Medium'),
('SAIF 11.2','Compliance Automation','Automate AI security compliance checks.','Medium'),
('SAIF 12.1','Third-Party AI Security','Assess security of third-party AI components.','Medium'),
('SAIF 12.2','AI Security Training','Train staff on AI security best practices.','Medium'),
('SAIF 13.1','Secure Prompt Engineering','Implement secure prompt engineering practices.','Medium'),
('SAIF 13.2','Output Sanitization','Sanitize AI system outputs before delivery.','Medium'),
('SAIF 14.1','Model Rollback Procedures','Establish procedures for AI model rollback.','Medium'),
('SAIF 14.2','AI Disaster Recovery','Implement disaster recovery for AI systems.','Medium'),
('SAIF 15.1','Threat Intelligence for AI','Integrate threat intelligence for AI security.','Medium'),
('SAIF 15.2','AI Security Metrics','Define and track AI security metrics.','Medium'),
('SAIF 16.1','Zero Trust for AI','Apply zero trust principles to AI infrastructure.','Medium'),
('SAIF 16.2','AI Secrets Management','Manage secrets and credentials for AI systems.','Medium')
) AS v(ref, name, desc, sev)
WHERE f.code='FW-009'
ON CONFLICT (framework_id, control_ref) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description;
