INSERT INTO controls (framework_id, control_ref, name, description, severity)
SELECT f.id, v.ref, v.name, v.desc, v.sev FROM frameworks f,
(VALUES
('Art. 6','Lawfulness of Processing','Ensure lawful basis for personal data processing.','Medium'),
('Art. 5.1b','Purpose Limitation','Limit data processing to specified purposes.','Medium'),
('Art. 5.1c','Data Minimization','Collect only necessary personal data.','Medium'),
('Art. 5.1d','Accuracy of Data','Maintain accuracy of personal data.','Medium'),
('Art. 5.1e','Storage Limitation','Limit storage duration of personal data.','Medium'),
('Art. 5.1f','Integrity & Confidentiality','Ensure security of personal data processing.','Medium'),
('Art. 7','Consent Management','Obtain and manage valid data subject consent.','Medium'),
('Art. 15','Right to Access','Enable data subjects to access their personal data.','Medium'),
('Art. 16','Right to Rectification','Enable data subjects to correct inaccurate data.','Medium'),
('Art. 17','Right to Erasure','Enable data subjects to request data deletion.','Medium'),
('Art. 20','Right to Portability','Enable data subjects to transfer their data.','Medium'),
('Art. 21','Right to Object','Enable data subjects to object to processing.','Medium'),
('Art. 22','Automated Decision Rights','Ensure rights around automated decision-making.','Medium'),
('Art. 25','Data Protection by Design','Implement data protection by design and default.','Medium'),
('Art. 35','Data Protection Impact Assessment','Conduct DPIAs for high-risk processing.','Medium'),
('Art. 33','Data Breach Notification','Notify supervisory authority of data breaches.','Medium'),
('Art. 34','Data Breach Communication','Communicate data breaches to affected individuals.','Medium'),
('Art. 37','DPO Appointment','Appoint Data Protection Officer where required.','Medium'),
('Art. 30','Records of Processing','Maintain records of processing activities.','Medium'),
('Art. 46','Cross-Border Transfer Safeguards','Implement safeguards for international transfers.','Medium'),
('Art. 28','Processor Agreements','Establish data processing agreements.','Medium'),
('Art. 26','Joint Controller Agreements','Establish joint controller arrangements.','Medium'),
('Art. 13','Privacy Notice Requirements','Provide transparent privacy notices.','Medium'),
('Art. 8','Children Data Protection','Protect personal data of children.','Medium'),
('Art. 9','Special Category Data','Control processing of special category data.','Medium'),
('Art. 31','Supervisory Authority Cooperation','Cooperate with supervisory authorities.','Medium'),
('Art. 42','Data Protection Certification','Obtain data protection certifications.','Medium'),
('Art. 40','Code of Conduct Adherence','Adhere to approved codes of conduct.','Medium'),
('Art. 18','Right to Restriction','Enable data subjects to restrict processing.','Medium'),
('Art. 6.1f','Legitimate Interest Assessment','Conduct legitimate interest assessments.','Medium'),
('Art. 12','Transparency of Processing','Ensure transparent communication about processing.','Medium'),
('Art. 32','Data Security Measures','Implement appropriate technical security measures.','Medium'),
('Art. 28.2','Sub-Processor Management','Manage and authorize sub-processors.','Medium'),
('Art. 49','International Transfer Mechanisms','Implement derogations for international transfers.','Medium'),
('Art. 12.3','Data Subject Request Handling','Handle data subject requests within timeframes.','Medium'),
('Art. 25.2','Privacy by Default','Implement privacy by default in data processing.','Medium'),
('Art. 36','Consultation with Authority','Consult supervisory authority for high-risk processing.','Medium'),
('Art. 27','Representative Appointment','Appoint representative in EU where required.','Medium'),
('Art. 88','Employee Data Protection','Protect employee personal data in employment.','Medium'),
('Art. 89','Research Data Safeguards','Safeguard data used for research purposes.','Medium')
) AS v(ref, name, desc, sev)
WHERE f.code='FW-007'
ON CONFLICT (framework_id, control_ref) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description;
