INSERT INTO controls (framework_id, control_ref, name, description, severity)
SELECT f.id, v.ref, v.name, v.desc, v.sev FROM frameworks f,
(VALUES
('Clause 5.2','AI Policy & Objectives','Establish and maintain AI policy aligned with organizational objectives.','Medium'),
('Clause 6.1','AI Risk Assessment Process','Systematic identification and evaluation of AI-related risks.','Medium'),
('Clause 6.1.2','AI Impact Assessment','Assess potential impacts of AI systems on stakeholders.','Medium'),
('Clause 5.3','Roles & Responsibilities for AI','Define clear roles for AI governance and operations.','Medium'),
('Clause 8.2','AI System Lifecycle Management','Manage AI systems throughout their complete lifecycle.','Medium'),
('Clause 8.4','Data Quality for AI Systems','Ensure data used in AI systems meets quality requirements.','Medium'),
('Clause 8.5','AI System Validation','Validate AI systems meet specified requirements.','Medium'),
('Clause 8.6','AI Transparency Requirements','Ensure AI system decisions are transparent and explainable.','Medium'),
('Clause 8.7','Third-Party AI Components','Manage risks from third-party AI components and services.','Medium'),
('Clause 7.2','AI Competence & Awareness','Ensure personnel have necessary AI competencies.','Medium'),
('Clause 7.5','AI System Documentation','Maintain comprehensive documentation for AI systems.','Medium'),
('Clause 9.1','AI Performance Monitoring','Monitor and measure AI system performance continuously.','Medium'),
('Clause 9.2','Internal Audit for AI','Conduct regular internal audits of AI management system.','Medium'),
('Clause 9.3','Management Review','Review AI management system at planned intervals.','Medium'),
('Clause 10.1','Continual Improvement','Continuously improve AI management system effectiveness.','Medium'),
('Clause 10.2','Nonconformity & Corrective Action','Address nonconformities and implement corrective actions.','Medium'),
('Clause 7.4','AI Stakeholder Communication','Communicate AI-related information to stakeholders.','Medium'),
('Clause 4.1','Context of Organization','Understand organizational context for AI management.','Medium'),
('Clause 4.2','Stakeholder Needs','Identify needs and expectations of interested parties.','Medium'),
('Clause 4.3','AIMS Scope Definition','Define scope of AI management system.','Medium'),
('Clause 5.1','Leadership Commitment','Demonstrate leadership commitment to AI management.','Medium'),
('Clause 7.1','AI Resource Management','Provide resources needed for AI management system.','Medium'),
('Clause 8.1','Operational Planning','Plan and control AI operational processes.','Medium'),
('Annex A.2','AI Bias Mitigation','Assess and mitigate bias in AI systems.','Medium'),
('Annex A.3','AI Fairness Controls','Implement controls to ensure AI system fairness.','Medium'),
('Annex A.4','Explainability Requirements','Ensure AI decisions can be explained to stakeholders.','Medium'),
('Annex A.5','AI Safety Controls','Implement safety measures for AI system operation.','Medium'),
('Annex A.6','AI Security Controls','Protect AI systems from security threats.','Medium'),
('Annex A.7','AI Privacy Controls','Protect personal data in AI system processing.','Medium'),
('Annex A.8','Human Oversight of AI','Maintain meaningful human oversight of AI systems.','Medium'),
('Annex A.9','Accountability Framework','Establish accountability for AI system outcomes.','Medium'),
('Annex A.10','Societal Impact Assessment','Assess broader societal impacts of AI systems.','Medium'),
('Annex B.1','Training Data Governance','Govern the selection and use of AI training data.','Medium'),
('Annex B.2','Model Selection & Design','Govern AI model selection and design processes.','Medium'),
('Annex B.3','AI Testing & Evaluation','Test and evaluate AI systems before deployment.','Medium'),
('Annex B.4','Deployment Controls','Control AI system deployment processes.','Medium'),
('Annex B.5','Decommissioning Procedures','Safely decommission AI systems when needed.','Medium'),
('Annex B.6','AI Incident Management','Manage incidents related to AI system operation.','Medium'),
('Annex B.7','Supplier AI Risk','Manage AI-related risks from suppliers.','Medium'),
('Annex B.8','Regulatory Compliance Tracking','Track compliance with AI regulations.','Medium'),
('Annex C.1','Ethics Committee Governance','Govern AI ethics committee operations.','Medium'),
('Annex C.2','Stakeholder Engagement','Engage stakeholders in AI governance.','Medium'),
('Annex C.3','AI Knowledge Management','Manage organizational AI knowledge.','Medium'),
('Annex C.4','Cross-Border Data Transfer','Control cross-border AI data transfers.','Medium'),
('Annex C.5','System Inventory Management','Maintain inventory of all AI systems.','Medium')
) AS v(ref, name, desc, sev)
WHERE f.code='FW-001'
ON CONFLICT (framework_id, control_ref) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description;
