INSERT INTO controls (framework_id, control_ref, name, description, severity)
SELECT f.id, v.ref, v.name, v.desc, v.sev FROM frameworks f,
(VALUES
('Art. 6','AI System Risk Classification','Classify all AI systems by risk level per EU AI Act categories.','Medium'),
('Art. 10','Data Governance for AI Training','Ensure training data quality relevance and representativeness.','Medium'),
('Art. 13','Transparency & Documentation','Provide transparent information about AI system capabilities.','Medium'),
('Art. 14','Human Oversight Mechanisms','Enable human oversight and intervention in AI decisions.','Medium'),
('Art. 15','Accuracy & Robustness','Ensure AI systems achieve appropriate accuracy and robustness.','Medium'),
('Art. 5','Prohibited AI Practices','Identify and prevent prohibited AI practices.','Medium'),
('Art. 8','High-Risk AI Requirements','Implement requirements for high-risk AI systems.','Medium'),
('Art. 9','Risk Management System','Establish risk management for high-risk AI systems.','Medium'),
('Art. 11','Technical Documentation','Maintain technical documentation for AI systems.','Medium'),
('Art. 12','Record-Keeping Requirements','Implement automatic logging for high-risk AI systems.','Medium'),
('Art. 43','Conformity Assessment','Conduct conformity assessments for high-risk AI.','Medium'),
('Art. 49','CE Marking & Registration','Ensure proper CE marking and EU database registration.','Medium'),
('Art. 72','Post-Market Monitoring','Establish post-market monitoring for AI systems.','Medium'),
('Art. 73','Serious Incident Reporting','Report serious incidents involving AI systems.','Medium'),
('Art. 53','General-Purpose AI Obligations','Comply with obligations for general-purpose AI models.','Medium'),
('Art. 55','Systemic Risk Assessment','Assess systemic risks of high-impact AI models.','Medium'),
('Art. 4','AI Literacy Requirements','Ensure AI literacy among staff operating AI systems.','Medium'),
('Art. 27','Fundamental Rights Impact','Assess impact on fundamental rights before deployment.','Medium'),
('Art. 50','Transparency for Users','Inform users when interacting with AI systems.','Medium'),
('Art. 26','Deployer Obligations','Fulfill obligations as AI system deployer.','Medium'),
('Art. 16','Provider Obligations','Fulfill obligations as AI system provider.','Medium'),
('Art. 22','Authorized Representative','Designate authorized representative where required.','Medium'),
('Art. 23','Importer Obligations','Fulfill obligations as AI system importer.','Medium'),
('Art. 24','Distributor Obligations','Fulfill obligations as AI system distributor.','Medium'),
('Art. 17','Quality Management System','Implement quality management system for AI.','Medium'),
('Art. 47','EU Declaration of Conformity','Prepare EU declaration of conformity.','Medium'),
('Art. 29','Notified Body Engagement','Engage notified bodies for conformity assessment.','Medium'),
('Art. 57','Sandbox Participation','Participate in AI regulatory sandboxes where applicable.','Medium'),
('Art. 7','Biometric AI Controls','Control use of biometric AI identification systems.','Medium'),
('Art. 50.3','Emotion Recognition Controls','Disclose emotion recognition AI system use.','Medium'),
('Art. 50.4','Deep Fake Disclosure','Disclose AI-generated or manipulated content.','Medium'),
('Art. 18','AI System Traceability','Ensure traceability of AI system decisions.','Medium'),
('Art. 20','Corrective Action Procedures','Implement corrective actions for non-conforming AI.','Medium'),
('Art. 74','Market Surveillance Cooperation','Cooperate with market surveillance authorities.','Medium'),
('Art. 56','Codes of Practice','Develop or adhere to AI codes of practice.','Medium'),
('Art. 10.5','Data Protection Compliance','Ensure AI data processing complies with GDPR.','Medium'),
('Art. 16.h','Accessibility Requirements','Ensure AI system accessibility for persons with disabilities.','Medium'),
('Art. 40','Environmental Sustainability','Consider environmental impact of AI systems.','Medium'),
('Art. 25','Cross-Border AI Deployment','Manage cross-border deployment requirements.','Medium'),
('Art. 21','AI System Withdrawal','Withdraw non-conforming AI systems from market.','Medium'),
('Art. 60','Testing in Real-World Conditions','Manage testing of AI in real-world conditions.','Medium'),
('Art. 61','Informed Consent for Testing','Obtain consent for real-world AI testing.','Medium'),
('Art. 28','Child Protection in AI','Protect children from harmful AI system effects.','Medium'),
('Art. 5.1c','Democratic Process Protection','Prevent AI manipulation of democratic processes.','Medium'),
('Art. 5.1c.2','Social Scoring Prevention','Prevent AI-based social scoring systems.','Medium'),
('Art. 26.7','Workplace AI Transparency','Inform workers about workplace AI systems.','Medium'),
('Annex III.5','Financial AI Risk Controls','Control AI risks in financial services.','Medium'),
('Annex III.1','Healthcare AI Validation','Validate AI systems used in healthcare.','Medium'),
('Annex III.2','Critical Infrastructure AI','Secure AI in critical infrastructure.','Medium'),
('Annex III.3','Education AI Safeguards','Safeguard AI use in education.','Medium'),
('Annex III.4','Employment AI Fairness','Ensure fairness in employment AI systems.','Medium'),
('Annex III.6','Law Enforcement AI Controls','Control AI use in law enforcement.','Medium'),
('Annex III.7','Immigration AI Controls','Control AI in immigration and border management.','Medium'),
('Annex III.8','Justice AI Safeguards','Safeguard AI use in justice administration.','Medium'),
('Art. 5.1d','Predictive Policing Controls','Control AI use in predictive policing.','Medium')
) AS v(ref, name, desc, sev)
WHERE f.code='FW-003'
ON CONFLICT (framework_id, control_ref) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description;
