INSERT INTO controls (framework_id, control_ref, name, description, severity)
SELECT f.id, v.ref, v.name, v.desc, v.sev FROM frameworks f,
(VALUES
('Val 1.1','Proportionality & Do No Harm','Ensure AI use is proportionate and does no harm.','Medium'),
('Val 1.2','Safety & Security','Ensure AI systems are safe and secure.','Medium'),
('Val 2.1','Right to Privacy','Protect right to privacy in AI systems.','Medium'),
('Val 2.2','Data Protection in AI','Implement data protection measures for AI.','Medium'),
('Val 3.1','Multi-Stakeholder Governance','Enable multi-stakeholder and adaptive AI governance.','Medium'),
('Val 3.2','Transparency & Explainability','Ensure AI transparency and explainability.','Medium'),
('Val 4.1','Responsibility & Accountability','Establish responsibility and accountability for AI.','Medium'),
('Val 4.2','Human Oversight & Determination','Maintain human oversight and determination over AI.','Medium'),
('Val 5.1','Awareness & Literacy','Promote AI awareness and literacy.','Medium'),
('Val 5.2','Inclusiveness & Equity','Ensure AI systems are inclusive and equitable.','Medium'),
('Val 5.3','Gender Equality in AI','Promote gender equality in AI development and use.','Medium'),
('Val 5.4','Cultural Diversity','Respect cultural diversity in AI systems.','Medium'),
('Val 6.1','Environment & Ecosystem','Protect environment and ecosystems from AI impacts.','Medium'),
('Val 6.2','AI for Sustainable Development','Use AI to support sustainable development goals.','Medium'),
('Val 7.1','Peace & Justice','Use AI to promote peace and justice.','Medium'),
('Val 7.2','Democratic Participation','Enable democratic participation through AI governance.','Medium'),
('Pol 1.1','AI Readiness Assessment','Assess organizational readiness for ethical AI.','Medium'),
('Pol 1.2','Impact Assessment Framework','Implement ethical impact assessment for AI.','Medium'),
('Pol 2.1','AI Governance Structure','Establish AI governance structures.','Medium'),
('Pol 3.1','International Cooperation','Promote international cooperation on AI ethics.','Medium'),
('Pol 4.1','Education & Research','Support AI ethics education and research.','Medium'),
('Pol 5.1','Health Sector AI Ethics','Apply AI ethics principles in health sector.','Medium'),
('Pol 5.2','Communication & Media AI','Apply AI ethics in communication and media.','Medium'),
('Pol 5.3','Economic Sector AI Ethics','Apply AI ethics in economic activities.','Medium'),
('Pol 5.4','Science & Technology AI','Apply AI ethics in science and technology.','Medium'),
('Val 5.5','Indigenous Knowledge Protection','Protect indigenous knowledge in AI systems.','Medium'),
('Val 7.3','Conflict Prevention','Prevent AI use in conflict escalation.','Medium'),
('Val 5.6','Digital Divide Reduction','Reduce digital divide through AI governance.','Medium'),
('Val 6.3','Water & Food Security AI','Apply AI ethics to water and food security.','Medium'),
('Val 6.4','Climate Action AI','Use AI responsibly for climate action.','Medium')
) AS v(ref, name, desc, sev)
WHERE f.code='FW-008'
ON CONFLICT (framework_id, control_ref) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description;
