-- ---------------------------------------------------------------------------
-- Seed: framework_controls catalog — Regulation & Ethics frameworks.
--
-- WHY. The five frameworks below already exist as `frameworks` rows but carry
-- an empty control catalog. This migration populates `public.framework_controls`
-- with the REAL, published controls of each, so the Frameworks page renders an
-- actual catalog instead of a bare count. All control_refs and titles are the
-- real published identifiers/headings drawn from the standards themselves:
--
--   * EU AI Act        — Regulation (EU) 2024/1689 (OJ L, 12.7.2024). The
--                        obligation-bearing Articles; control_ref = 'Art. N',
--                        domain = the Chapter/Section grouping; verbatim titles.
--   * GDPR             — Regulation (EU) 2016/679. The substantive obligation
--                        Articles (Chapters II–V); control_ref = 'Art. N'.
--   * OECD AI          — OECD AI Principles, Recommendation of the Council on
--                        AI [OECD/LEGAL/0449], 2019 as revised May 2024. The 5
--                        values-based principles (1.1–1.5) + 5 recommendations
--                        to policymakers (2.1–2.5); OECD's own numbering.
--   * Singapore Model  — Model AI Governance Framework, Second Edition (IMDA/PDPC,
--                        2020). The recommendations across the four pillars.
--                        The Model Framework publishes narrative guidance with
--                        NO official control codes; refs here are pillar-prefixed
--                        positional indices (IG/HI/OM/SC), while every title is
--                        the framework's real section heading.
--   * UNESCO AI Ethics — Recommendation on the Ethics of Artificial Intelligence
--                        (UNESCO, 2021). The 4 core values + 10 principles + 11
--                        Areas of Policy Action, using UNESCO's own numbering.
--
-- Idempotent: ON CONFLICT (id) DO UPDATE; safe to replay from zero. org_id is
-- the demo org; framework_id references pre-existing frameworks rows (not
-- recreated here). Single quotes in text are escaped by doubling.
-- ---------------------------------------------------------------------------

-- framework_controls.org_id was added by the ws01 tenancy sweep via a dynamic
-- EXECUTE format('ALTER TABLE public.%I ADD COLUMN org_id ...') loop, which a
-- static from-zero replay parser cannot attribute to this table. Re-assert it
-- idempotently here (a no-op on the live DB where the column already exists) so
-- the INSERTs below have a recognised column to target. See 20260826000001 for
-- the DB-filled default rationale.
ALTER TABLE public.framework_controls
  ADD COLUMN IF NOT EXISTS org_id uuid DEFAULT current_user_org_id();

-- ===========================================================================
-- 1. EU AI ACT — Regulation (EU) 2024/1689
-- ===========================================================================
INSERT INTO public.framework_controls
  (id, org_id, framework_id, control_ref, domain, title, description, control_type, priority)
VALUES
  ('fc-eu-ai-act-art-5', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 5', 'Chapter II — Prohibited AI Practices', 'Prohibited AI practices',
   'Prohibits AI practices including subliminal or purposefully manipulative techniques, exploitation of vulnerabilities, social scoring, certain biometric categorisation, untargeted scraping of facial images, emotion recognition in the workplace and education, and (subject to narrow exceptions) real-time remote biometric identification in publicly accessible spaces for law enforcement.',
   'preventive', 'high'),
  ('fc-eu-ai-act-art-6', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 6', 'Chapter III, Section 1 — Classification of AI Systems as High-Risk', 'Classification rules for high-risk AI systems',
   'Sets the rules for classifying an AI system as high-risk: systems that are safety components of products covered by the Annex I harmonisation legislation, and the use cases listed in Annex III.',
   'governance', 'high'),
  ('fc-eu-ai-act-art-7', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 7', 'Chapter III, Section 1 — Classification of AI Systems as High-Risk', 'Amendments to Annex III',
   'Empowers the Commission to amend, by delegated act, the Annex III list of high-risk use cases under defined conditions.',
   'governance', 'low'),
  ('fc-eu-ai-act-art-8', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 8', 'Chapter III, Section 2 — Requirements for High-Risk AI Systems', 'Compliance with the requirements',
   'High-risk AI systems shall comply with the requirements of this Section, taking into account their intended purpose and the generally acknowledged state of the art.',
   'governance', 'high'),
  ('fc-eu-ai-act-art-9', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 9', 'Chapter III, Section 2 — Requirements for High-Risk AI Systems', 'Risk management system',
   'A risk management system shall be established, implemented, documented and maintained throughout the entire lifecycle of a high-risk AI system as a continuous iterative process, identifying and mitigating reasonably foreseeable risks.',
   'governance', 'high'),
  ('fc-eu-ai-act-art-10', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 10', 'Chapter III, Section 2 — Requirements for High-Risk AI Systems', 'Data and data governance',
   'Training, validation and testing data sets shall be subject to appropriate data governance and management practices and meet quality criteria — relevance, sufficient representativeness, and to the best extent possible freedom from errors and completeness — in view of the intended purpose.',
   'governance', 'high'),
  ('fc-eu-ai-act-art-11', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 11', 'Chapter III, Section 2 — Requirements for High-Risk AI Systems', 'Technical documentation',
   'Technical documentation shall be drawn up before the system is placed on the market or put into service and kept up to date, containing at least the elements set out in Annex IV to demonstrate conformity.',
   'administrative', 'high'),
  ('fc-eu-ai-act-art-12', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 12', 'Chapter III, Section 2 — Requirements for High-Risk AI Systems', 'Record-keeping',
   'High-risk AI systems shall technically allow for the automatic recording of events (logs) over the lifetime of the system, to ensure a level of traceability appropriate to the intended purpose.',
   'detective', 'high'),
  ('fc-eu-ai-act-art-13', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 13', 'Chapter III, Section 2 — Requirements for High-Risk AI Systems', 'Transparency and provision of information to deployers',
   'High-risk AI systems shall be designed to be sufficiently transparent to enable deployers to interpret the output and use it appropriately, and shall be accompanied by instructions for use containing concise, complete and relevant information.',
   'administrative', 'high'),
  ('fc-eu-ai-act-art-14', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 14', 'Chapter III, Section 2 — Requirements for High-Risk AI Systems', 'Human oversight',
   'High-risk AI systems shall be designed and developed so they can be effectively overseen by natural persons during use, including the ability to understand the system, monitor its operation, and intervene in or interrupt it.',
   'governance', 'high'),
  ('fc-eu-ai-act-art-15', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 15', 'Chapter III, Section 2 — Requirements for High-Risk AI Systems', 'Accuracy, robustness and cybersecurity',
   'High-risk AI systems shall be designed to achieve appropriate levels of accuracy, robustness and cybersecurity, and to perform consistently in those respects throughout their lifecycle.',
   'technical', 'high'),
  ('fc-eu-ai-act-art-16', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 16', 'Chapter III, Section 3 — Obligations of Providers and Deployers of High-Risk AI Systems', 'Obligations of providers of high-risk AI systems',
   'Providers shall ensure conformity with the requirements, operate a quality management system, keep documentation and logs, undergo the relevant conformity assessment, affix the CE marking, register, and take corrective action.',
   'governance', 'high'),
  ('fc-eu-ai-act-art-17', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 17', 'Chapter III, Section 3 — Obligations of Providers and Deployers of High-Risk AI Systems', 'Quality management system',
   'Providers shall put in place a documented quality management system that ensures compliance with the Regulation, covering strategies, procedures, testing, data management, risk management and post-market monitoring.',
   'governance', 'high'),
  ('fc-eu-ai-act-art-18', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 18', 'Chapter III, Section 3 — Obligations of Providers and Deployers of High-Risk AI Systems', 'Documentation keeping',
   'Providers shall keep the technical documentation, quality management system documentation, and any approvals or decisions at the disposal of national competent authorities for 10 years after the system is placed on the market.',
   'administrative', 'medium'),
  ('fc-eu-ai-act-art-19', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 19', 'Chapter III, Section 3 — Obligations of Providers and Deployers of High-Risk AI Systems', 'Automatically generated logs',
   'Providers shall keep the logs automatically generated by their high-risk AI systems, to the extent such logs are under their control, for an appropriate period in light of the intended purpose.',
   'detective', 'medium'),
  ('fc-eu-ai-act-art-20', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 20', 'Chapter III, Section 3 — Obligations of Providers and Deployers of High-Risk AI Systems', 'Corrective actions and duty of information',
   'Providers who consider or have reason to consider a system to be non-conforming shall immediately take the necessary corrective actions, withdraw or recall it as appropriate, and inform the relevant authorities and operators.',
   'corrective', 'high'),
  ('fc-eu-ai-act-art-21', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 21', 'Chapter III, Section 3 — Obligations of Providers and Deployers of High-Risk AI Systems', 'Cooperation with competent authorities',
   'Providers shall, upon a reasoned request from a competent authority, provide all the information and documentation necessary to demonstrate the conformity of the high-risk AI system.',
   'administrative', 'medium'),
  ('fc-eu-ai-act-art-22', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 22', 'Chapter III, Section 3 — Obligations of Providers and Deployers of High-Risk AI Systems', 'Authorised representatives of providers of high-risk AI systems',
   'Providers established in third countries shall, prior to making their systems available on the Union market, appoint by written mandate an authorised representative established in the Union.',
   'administrative', 'medium'),
  ('fc-eu-ai-act-art-23', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 23', 'Chapter III, Section 3 — Obligations of Providers and Deployers of High-Risk AI Systems', 'Obligations of importers',
   'Before placing a high-risk AI system on the market, importers shall verify that the conformity assessment has been carried out, the technical documentation drawn up, the CE marking affixed, and the required documents provided.',
   'preventive', 'medium'),
  ('fc-eu-ai-act-art-24', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 24', 'Chapter III, Section 3 — Obligations of Providers and Deployers of High-Risk AI Systems', 'Obligations of distributors',
   'Before making a high-risk AI system available, distributors shall verify that it bears the CE marking, is accompanied by the required documentation and instructions, and that the provider and importer have complied with their obligations.',
   'preventive', 'medium'),
  ('fc-eu-ai-act-art-25', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 25', 'Chapter III, Section 3 — Obligations of Providers and Deployers of High-Risk AI Systems', 'Responsibilities along the AI value chain',
   'Sets the circumstances in which a distributor, importer, deployer or other third party is considered a provider and assumes the corresponding obligations, and requires cooperation and information-sharing along the AI value chain.',
   'governance', 'medium'),
  ('fc-eu-ai-act-art-26', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 26', 'Chapter III, Section 3 — Obligations of Providers and Deployers of High-Risk AI Systems', 'Obligations of deployers of high-risk AI systems',
   'Deployers shall use high-risk AI systems in accordance with the instructions, assign competent human oversight, ensure input data are relevant, monitor operation, keep logs, and inform providers and authorities of risks and incidents.',
   'governance', 'high'),
  ('fc-eu-ai-act-art-27', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 27', 'Chapter III, Section 3 — Obligations of Providers and Deployers of High-Risk AI Systems', 'Fundamental rights impact assessment for high-risk AI systems',
   'Deployers that are bodies governed by public law or private entities providing public services, and deployers of certain Annex III systems, shall perform an assessment of the impact on fundamental rights prior to deployment.',
   'detective', 'high'),
  ('fc-eu-ai-act-art-43', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 43', 'Chapter III, Section 5 — Standards, Conformity Assessment, Certificates, Registration', 'Conformity assessment',
   'High-risk AI systems shall undergo the applicable conformity assessment procedure (based on internal control or involving a notified body) before being placed on the market or put into service, and again upon substantial modification.',
   'detective', 'high'),
  ('fc-eu-ai-act-art-47', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 47', 'Chapter III, Section 5 — Standards, Conformity Assessment, Certificates, Registration', 'EU declaration of conformity',
   'The provider shall draw up a written, machine-readable EU declaration of conformity for each high-risk AI system, keep it for 10 years, and make it available to the competent authorities.',
   'administrative', 'medium'),
  ('fc-eu-ai-act-art-48', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 48', 'Chapter III, Section 5 — Standards, Conformity Assessment, Certificates, Registration', 'CE marking',
   'The CE marking of conformity shall be affixed visibly, legibly and indelibly for high-risk AI systems (or on packaging/documentation where not possible), indicating conformity with the Regulation.',
   'administrative', 'medium'),
  ('fc-eu-ai-act-art-49', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 49', 'Chapter III, Section 5 — Standards, Conformity Assessment, Certificates, Registration', 'Registration',
   'Before placing on the market or putting into service a high-risk AI system listed in Annex III, the provider or, where applicable, the authorised representative or deployer, shall register it in the EU database.',
   'administrative', 'high'),
  ('fc-eu-ai-act-art-50', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 50', 'Chapter IV — Transparency Obligations for Providers and Deployers of Certain AI Systems', 'Transparency obligations for providers and deployers of certain AI systems',
   'Providers shall ensure people are informed when interacting with an AI system, and that synthetic audio, image, video or text is marked as artificially generated; deployers shall disclose deep fakes and AI-generated text informing the public on matters of public interest.',
   'administrative', 'high'),
  ('fc-eu-ai-act-art-51', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 51', 'Chapter V — General-Purpose AI Models', 'Classification of general-purpose AI models as general-purpose AI models with systemic risk',
   'Establishes the criteria for classifying a general-purpose AI model as presenting systemic risk, including high-impact capabilities and the presumption where cumulative training compute exceeds 10^25 floating-point operations.',
   'governance', 'high'),
  ('fc-eu-ai-act-art-52', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 52', 'Chapter V — General-Purpose AI Models', 'Procedure',
   'Sets the procedure by which a general-purpose AI model is designated as having systemic risk, including notification to the Commission and the possibility for providers to contest the designation.',
   'governance', 'medium'),
  ('fc-eu-ai-act-art-53', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 53', 'Chapter V — General-Purpose AI Models', 'Obligations for providers of general-purpose AI models',
   'Providers of general-purpose AI models shall draw up and keep technical documentation, provide information to downstream providers, put in place a policy to comply with Union copyright law, and publish a sufficiently detailed summary of the training content.',
   'governance', 'high'),
  ('fc-eu-ai-act-art-55', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 55', 'Chapter V — General-Purpose AI Models', 'Obligations of providers of general-purpose AI models with systemic risk',
   'Providers of GPAI models with systemic risk shall perform model evaluation and adversarial testing, assess and mitigate systemic risks, track and report serious incidents, and ensure an adequate level of cybersecurity protection.',
   'governance', 'high'),
  ('fc-eu-ai-act-art-72', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 72', 'Chapter IX — Post-Market Monitoring, Information Sharing and Market Surveillance', 'Post-market monitoring by providers and post-market monitoring plan for high-risk AI systems',
   'Providers shall establish and document a post-market monitoring system proportionate to the risks, actively collecting and analysing performance data over the system''s lifetime to evaluate continued compliance.',
   'detective', 'high'),
  ('fc-eu-ai-act-art-73', '00000000-0000-0000-0000-000000000001', 'eu-ai-act',
   'Art. 73', 'Chapter IX — Post-Market Monitoring, Information Sharing and Market Surveillance', 'Reporting of serious incidents',
   'Providers of high-risk AI systems placed on the Union market shall report any serious incident to the relevant market surveillance authorities within the deadlines set by the Regulation.',
   'corrective', 'high')
ON CONFLICT (id) DO UPDATE SET
  control_ref = EXCLUDED.control_ref, domain = EXCLUDED.domain,
  title = EXCLUDED.title, description = EXCLUDED.description,
  control_type = EXCLUDED.control_type, priority = EXCLUDED.priority;

-- ===========================================================================
-- 2. GDPR — Regulation (EU) 2016/679
-- ===========================================================================
INSERT INTO public.framework_controls
  (id, org_id, framework_id, control_ref, domain, title, description, control_type, priority)
VALUES
  ('fc-gdpr-art-5', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 5', 'Chapter II — Principles', 'Principles relating to processing of personal data',
   'Personal data shall be processed lawfully, fairly and transparently; collected for specified, explicit and legitimate purposes; adequate and limited to what is necessary; accurate; kept no longer than necessary; and processed securely — with the controller accountable for, and able to demonstrate, compliance.',
   'governance', 'high'),
  ('fc-gdpr-art-6', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 6', 'Chapter II — Principles', 'Lawfulness of processing',
   'Processing is lawful only if and to the extent that at least one legal basis applies: consent, contract, legal obligation, vital interests, public task, or legitimate interests.',
   'governance', 'high'),
  ('fc-gdpr-art-7', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 7', 'Chapter II — Principles', 'Conditions for consent',
   'Where processing is based on consent, the controller shall be able to demonstrate that the data subject consented; consent must be freely given, specific, informed and unambiguous, and withdrawable at any time.',
   'administrative', 'high'),
  ('fc-gdpr-art-8', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 8', 'Chapter II — Principles', 'Conditions applicable to child''s consent in relation to information society services',
   'Where information society services are offered directly to a child, consent-based processing is lawful only where the child is at least 16 (Member States may set a lower age, not below 13) or authorisation is given by the holder of parental responsibility.',
   'administrative', 'medium'),
  ('fc-gdpr-art-9', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 9', 'Chapter II — Principles', 'Processing of special categories of personal data',
   'Processing of special categories of personal data (e.g. racial or ethnic origin, political opinions, health, biometric or genetic data, sexual orientation) is prohibited unless one of the specific exceptions applies.',
   'preventive', 'high'),
  ('fc-gdpr-art-10', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 10', 'Chapter II — Principles', 'Processing of personal data relating to criminal convictions and offences',
   'Processing of personal data relating to criminal convictions and offences may be carried out only under the control of official authority or when authorised by Union or Member State law providing appropriate safeguards.',
   'governance', 'medium'),
  ('fc-gdpr-art-11', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 11', 'Chapter II — Principles', 'Processing which does not require identification',
   'Where the purposes do not or no longer require identification of a data subject, the controller is not obliged to maintain, acquire or process additional information solely to comply with the Regulation.',
   'governance', 'low'),
  ('fc-gdpr-art-12', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 12', 'Chapter III — Rights of the Data Subject', 'Transparent information, communication and modalities for the exercise of the rights of the data subject',
   'The controller shall provide information and communications relating to processing in a concise, transparent, intelligible and easily accessible form, and facilitate the exercise of data subject rights, generally free of charge and within one month.',
   'administrative', 'high'),
  ('fc-gdpr-art-13', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 13', 'Chapter III — Rights of the Data Subject', 'Information to be provided where personal data are collected from the data subject',
   'Where personal data are collected from the data subject, the controller shall, at the time of collection, provide specified information including identity, purposes and legal basis, recipients, retention period and the data subject''s rights.',
   'administrative', 'high'),
  ('fc-gdpr-art-14', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 14', 'Chapter III — Rights of the Data Subject', 'Information to be provided where personal data have not been obtained from the data subject',
   'Where personal data have not been obtained from the data subject, the controller shall provide specified information within a reasonable period (at latest within one month), unless an exemption applies.',
   'administrative', 'medium'),
  ('fc-gdpr-art-15', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 15', 'Chapter III — Rights of the Data Subject', 'Right of access by the data subject',
   'The data subject has the right to obtain confirmation of whether their personal data are being processed and, where so, access to the data and information about the processing.',
   'administrative', 'high'),
  ('fc-gdpr-art-16', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 16', 'Chapter III — Rights of the Data Subject', 'Right to rectification',
   'The data subject has the right to obtain from the controller, without undue delay, the rectification of inaccurate personal data and the completion of incomplete data.',
   'corrective', 'medium'),
  ('fc-gdpr-art-17', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 17', 'Chapter III — Rights of the Data Subject', 'Right to erasure (''right to be forgotten'')',
   'The data subject has the right to obtain erasure of personal data without undue delay where one of the specified grounds applies, and the controller shall take reasonable steps to inform other controllers processing the data.',
   'corrective', 'high'),
  ('fc-gdpr-art-18', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 18', 'Chapter III — Rights of the Data Subject', 'Right to restriction of processing',
   'The data subject has the right to obtain restriction of processing where accuracy is contested, processing is unlawful, the data are no longer needed but required by the subject, or an objection is pending verification.',
   'administrative', 'medium'),
  ('fc-gdpr-art-19', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 19', 'Chapter III — Rights of the Data Subject', 'Notification obligation regarding rectification or erasure of personal data or restriction of processing',
   'The controller shall communicate any rectification, erasure or restriction of processing to each recipient to whom the personal data have been disclosed, unless this proves impossible or involves disproportionate effort.',
   'administrative', 'low'),
  ('fc-gdpr-art-20', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 20', 'Chapter III — Rights of the Data Subject', 'Right to data portability',
   'The data subject has the right to receive their personal data in a structured, commonly used, machine-readable format and to transmit it to another controller where processing is based on consent or contract and carried out by automated means.',
   'administrative', 'medium'),
  ('fc-gdpr-art-21', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 21', 'Chapter III — Rights of the Data Subject', 'Right to object',
   'The data subject has the right to object, on grounds relating to their particular situation, to processing based on public task or legitimate interests, and an absolute right to object to processing for direct marketing.',
   'administrative', 'medium'),
  ('fc-gdpr-art-22', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 22', 'Chapter III — Rights of the Data Subject', 'Automated individual decision-making, including profiling',
   'The data subject has the right not to be subject to a decision based solely on automated processing, including profiling, which produces legal effects or similarly significantly affects them, save for defined exceptions with safeguards.',
   'preventive', 'high'),
  ('fc-gdpr-art-24', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 24', 'Chapter IV — Controller and Processor', 'Responsibility of the controller',
   'The controller shall implement appropriate technical and organisational measures to ensure and be able to demonstrate that processing is performed in accordance with the Regulation, reviewed and updated where necessary.',
   'governance', 'high'),
  ('fc-gdpr-art-25', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 25', 'Chapter IV — Controller and Processor', 'Data protection by design and by default',
   'The controller shall implement data protection by design and by default, integrating appropriate safeguards into the processing and ensuring that, by default, only personal data necessary for each specific purpose are processed.',
   'technical', 'high'),
  ('fc-gdpr-art-26', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 26', 'Chapter IV — Controller and Processor', 'Joint controllers',
   'Where two or more controllers jointly determine the purposes and means of processing, they shall in a transparent arrangement determine their respective responsibilities for compliance.',
   'governance', 'medium'),
  ('fc-gdpr-art-27', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 27', 'Chapter IV — Controller and Processor', 'Representatives of controllers or processors not established in the Union',
   'Controllers or processors not established in the Union that are subject to the Regulation under Article 3(2) shall designate in writing a representative in the Union.',
   'administrative', 'medium'),
  ('fc-gdpr-art-28', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 28', 'Chapter IV — Controller and Processor', 'Processor',
   'Processing by a processor shall be governed by a contract or other legal act binding the processor to the controller, setting out the subject-matter, duration, nature and purpose of processing and the specified obligations.',
   'governance', 'high'),
  ('fc-gdpr-art-29', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 29', 'Chapter IV — Controller and Processor', 'Processing under the authority of the controller or processor',
   'The processor and any person acting under the authority of the controller or processor with access to personal data shall not process them except on instructions from the controller, unless required by law.',
   'governance', 'medium'),
  ('fc-gdpr-art-30', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 30', 'Chapter IV — Controller and Processor', 'Records of processing activities',
   'Each controller and processor shall maintain a record of processing activities under its responsibility, containing the information specified, and make it available to the supervisory authority on request.',
   'detective', 'high'),
  ('fc-gdpr-art-31', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 31', 'Chapter IV — Controller and Processor', 'Cooperation with the supervisory authority',
   'The controller and processor shall cooperate, on request, with the supervisory authority in the performance of its tasks.',
   'administrative', 'low'),
  ('fc-gdpr-art-32', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 32', 'Chapter IV — Controller and Processor', 'Security of processing',
   'The controller and processor shall implement appropriate technical and organisational measures to ensure a level of security appropriate to the risk, including as appropriate pseudonymisation and encryption, and the confidentiality, integrity, availability and resilience of systems.',
   'technical', 'high'),
  ('fc-gdpr-art-33', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 33', 'Chapter IV — Controller and Processor', 'Notification of a personal data breach to the supervisory authority',
   'In the case of a personal data breach, the controller shall notify the competent supervisory authority without undue delay and, where feasible, not later than 72 hours after becoming aware of it, unless the breach is unlikely to result in a risk.',
   'corrective', 'high'),
  ('fc-gdpr-art-34', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 34', 'Chapter IV — Controller and Processor', 'Communication of a personal data breach to the data subject',
   'When a personal data breach is likely to result in a high risk to the rights and freedoms of natural persons, the controller shall communicate the breach to the data subject without undue delay.',
   'corrective', 'high'),
  ('fc-gdpr-art-35', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 35', 'Chapter IV — Controller and Processor', 'Data protection impact assessment',
   'Where a type of processing is likely to result in a high risk to the rights and freedoms of natural persons, the controller shall, prior to processing, carry out a data protection impact assessment.',
   'detective', 'high'),
  ('fc-gdpr-art-36', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 36', 'Chapter IV — Controller and Processor', 'Prior consultation',
   'The controller shall consult the supervisory authority prior to processing where a data protection impact assessment indicates that the processing would result in a high risk in the absence of mitigating measures.',
   'detective', 'medium'),
  ('fc-gdpr-art-37', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 37', 'Chapter IV — Controller and Processor', 'Designation of the data protection officer',
   'The controller and processor shall designate a data protection officer where processing is carried out by a public authority, or where core activities require regular and systematic large-scale monitoring or large-scale processing of special categories of data.',
   'governance', 'medium'),
  ('fc-gdpr-art-38', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 38', 'Chapter IV — Controller and Processor', 'Position of the data protection officer',
   'The controller and processor shall ensure the data protection officer is involved properly and in a timely manner in all issues relating to protection of personal data, supported with resources, and able to act independently.',
   'governance', 'low'),
  ('fc-gdpr-art-39', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 39', 'Chapter IV — Controller and Processor', 'Tasks of the data protection officer',
   'The data protection officer shall inform and advise on obligations, monitor compliance, provide advice on data protection impact assessments, and cooperate with and act as contact point for the supervisory authority.',
   'governance', 'low'),
  ('fc-gdpr-art-44', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 44', 'Chapter V — Transfers of Personal Data to Third Countries or International Organisations', 'General principle for transfers',
   'Any transfer of personal data undergoing processing to a third country or international organisation shall take place only in compliance with the conditions of Chapter V, to ensure the level of protection is not undermined.',
   'governance', 'high'),
  ('fc-gdpr-art-45', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 45', 'Chapter V — Transfers of Personal Data to Third Countries or International Organisations', 'Transfers on the basis of an adequacy decision',
   'A transfer may take place where the Commission has decided that the third country, territory, sector or international organisation ensures an adequate level of data protection.',
   'governance', 'medium'),
  ('fc-gdpr-art-46', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 46', 'Chapter V — Transfers of Personal Data to Third Countries or International Organisations', 'Transfers subject to appropriate safeguards',
   'In the absence of an adequacy decision, a transfer may take place only where the controller or processor has provided appropriate safeguards (e.g. standard contractual clauses, binding corporate rules, approved codes or certifications) and enforceable data subject rights.',
   'governance', 'high'),
  ('fc-gdpr-art-47', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 47', 'Chapter V — Transfers of Personal Data to Third Countries or International Organisations', 'Binding corporate rules',
   'The competent supervisory authority shall approve binding corporate rules provided they are legally binding, apply to and are enforced by every member of the group, and expressly confer enforceable rights on data subjects.',
   'governance', 'medium'),
  ('fc-gdpr-art-49', '00000000-0000-0000-0000-000000000001', 'gdpr',
   'Art. 49', 'Chapter V — Transfers of Personal Data to Third Countries or International Organisations', 'Derogations for specific situations',
   'In the absence of an adequacy decision or appropriate safeguards, a transfer may take place only under one of the specified derogations, such as explicit consent, contract performance, important reasons of public interest, or legal claims.',
   'governance', 'medium')
ON CONFLICT (id) DO UPDATE SET
  control_ref = EXCLUDED.control_ref, domain = EXCLUDED.domain,
  title = EXCLUDED.title, description = EXCLUDED.description,
  control_type = EXCLUDED.control_type, priority = EXCLUDED.priority;

-- ===========================================================================
-- 3. OECD AI PRINCIPLES — Recommendation of the Council on AI
--    [OECD/LEGAL/0449], 2019 as revised May 2024
-- ===========================================================================
INSERT INTO public.framework_controls
  (id, org_id, framework_id, control_ref, domain, title, description, control_type, priority)
VALUES
  ('fc-oecd-ai-1-1', '00000000-0000-0000-0000-000000000001', 'oecd-ai',
   '1.1', 'Principles for Responsible Stewardship of Trustworthy AI', 'Inclusive growth, sustainable development and well-being',
   'Stakeholders should proactively engage in responsible stewardship of trustworthy AI in pursuit of beneficial outcomes for people and the planet, such as augmenting human capabilities, enhancing inclusion, reducing inequalities and protecting the environment.',
   'governance', 'high'),
  ('fc-oecd-ai-1-2', '00000000-0000-0000-0000-000000000001', 'oecd-ai',
   '1.2', 'Principles for Responsible Stewardship of Trustworthy AI', 'Respect for the rule of law, human rights and democratic values, including fairness and privacy',
   'AI actors should respect the rule of law, human rights, democratic and human-centred values throughout the AI system lifecycle — including non-discrimination and equality, fairness, social justice, privacy and data protection, and internationally recognised labour rights.',
   'governance', 'high'),
  ('fc-oecd-ai-1-3', '00000000-0000-0000-0000-000000000001', 'oecd-ai',
   '1.3', 'Principles for Responsible Stewardship of Trustworthy AI', 'Transparency and explainability',
   'AI actors should commit to transparency and responsible disclosure regarding AI systems, providing meaningful information appropriate to context to foster general understanding, awareness of interactions, and the ability to understand and challenge AI outcomes.',
   'administrative', 'high'),
  ('fc-oecd-ai-1-4', '00000000-0000-0000-0000-000000000001', 'oecd-ai',
   '1.4', 'Principles for Responsible Stewardship of Trustworthy AI', 'Robustness, security and safety',
   'AI systems should be robust, secure and safe throughout their entire lifecycle so that, in conditions of normal use, foreseeable use or misuse, they function appropriately and do not pose unreasonable safety or security risks, with traceability and risk management applied.',
   'technical', 'high'),
  ('fc-oecd-ai-1-5', '00000000-0000-0000-0000-000000000001', 'oecd-ai',
   '1.5', 'Principles for Responsible Stewardship of Trustworthy AI', 'Accountability',
   'AI actors should be accountable for the proper functioning of AI systems and for respect of the AI principles, based on their roles, the context, and consistent with the state of the art, including traceability and the application of a systematic risk management approach.',
   'governance', 'high'),
  ('fc-oecd-ai-2-1', '00000000-0000-0000-0000-000000000001', 'oecd-ai',
   '2.1', 'National Policies and International Co-operation for Trustworthy AI', 'Investing in AI research and development',
   'Governments should consider long-term public investment, and encourage private investment, in research and development — including interdisciplinary efforts — to spur innovation in trustworthy AI focused on challenging technical issues and social, legal and ethical implications.',
   'governance', 'medium'),
  ('fc-oecd-ai-2-2', '00000000-0000-0000-0000-000000000001', 'oecd-ai',
   '2.2', 'National Policies and International Co-operation for Trustworthy AI', 'Fostering an inclusive AI-enabling ecosystem',
   'Governments should foster the development of, and access to, an inclusive, dynamic, sustainable and interoperable digital ecosystem for trustworthy AI, including digital technologies and infrastructure and mechanisms for sharing AI knowledge.',
   'governance', 'medium'),
  ('fc-oecd-ai-2-3', '00000000-0000-0000-0000-000000000001', 'oecd-ai',
   '2.3', 'National Policies and International Co-operation for Trustworthy AI', 'Shaping an enabling interoperable governance and policy environment for AI',
   'Governments should promote an agile policy environment that supports transition from research to deployment and operation, including experimentation, and review and adapt policy and regulatory frameworks and assessment mechanisms as needed.',
   'governance', 'medium'),
  ('fc-oecd-ai-2-4', '00000000-0000-0000-0000-000000000001', 'oecd-ai',
   '2.4', 'National Policies and International Co-operation for Trustworthy AI', 'Building human capacity and preparing for labour market transition',
   'Governments should empower people to effectively use and interact with AI systems, equip workers with the skills to benefit from new opportunities, and support workers and ensure a fair transition through the changes AI brings to the world of work.',
   'governance', 'medium'),
  ('fc-oecd-ai-2-5', '00000000-0000-0000-0000-000000000001', 'oecd-ai',
   '2.5', 'National Policies and International Co-operation for Trustworthy AI', 'International co-operation for trustworthy AI',
   'Governments should co-operate across borders and sectors to share knowledge, promote responsible stewardship of trustworthy AI, and work towards developing and using internationally comparable metrics and interoperable standards and frameworks.',
   'governance', 'medium')
ON CONFLICT (id) DO UPDATE SET
  control_ref = EXCLUDED.control_ref, domain = EXCLUDED.domain,
  title = EXCLUDED.title, description = EXCLUDED.description,
  control_type = EXCLUDED.control_type, priority = EXCLUDED.priority;

-- ===========================================================================
-- 4. SINGAPORE MODEL AI GOVERNANCE FRAMEWORK — Second Edition (IMDA/PDPC, 2020)
--    Narrative guidance with no official codes; refs are pillar-prefixed
--    positional indices, titles are the framework's real section headings.
-- ===========================================================================
INSERT INTO public.framework_controls
  (id, org_id, framework_id, control_ref, domain, title, description, control_type, priority)
VALUES
  ('fc-singapore-ai-ig-1', '00000000-0000-0000-0000-000000000001', 'singapore-ai',
   'IG.1', 'Internal Governance Structures and Measures', 'Clear roles and responsibilities for the ethical deployment of AI',
   'Establish clear internal governance structures and measures, allocating roles and responsibilities to the personnel and functions responsible for the organisation''s AI adoption, including oversight of the associated risks.',
   'governance', 'high'),
  ('fc-singapore-ai-ig-2', '00000000-0000-0000-0000-000000000001', 'singapore-ai',
   'IG.2', 'Internal Governance Structures and Measures', 'Risk management and internal controls',
   'Implement risk management and internal control measures — such as standard operating procedures, sound data accountability practices, and monitoring — appropriate to the materiality and complexity of the AI systems deployed.',
   'governance', 'high'),
  ('fc-singapore-ai-hi-1', '00000000-0000-0000-0000-000000000001', 'singapore-ai',
   'HI.1', 'Determining the Level of Human Involvement in AI-augmented Decision-Making', 'Determining an appropriate level of human involvement in AI-augmented decision-making',
   'Adopt a methodology to determine the appropriate degree of human involvement in AI-augmented decision-making, weighing the organisation''s commercial objectives against the probability and severity of harm to individuals.',
   'governance', 'high'),
  ('fc-singapore-ai-hi-2', '00000000-0000-0000-0000-000000000001', 'singapore-ai',
   'HI.2', 'Determining the Level of Human Involvement in AI-augmented Decision-Making', 'Human-in-the-loop',
   'A model of oversight in which human decision-makers retain full control and the AI system only provides recommendations or input, with a human making the decision.',
   'governance', 'medium'),
  ('fc-singapore-ai-hi-3', '00000000-0000-0000-0000-000000000001', 'singapore-ai',
   'HI.3', 'Determining the Level of Human Involvement in AI-augmented Decision-Making', 'Human-out-of-the-loop',
   'A model of oversight in which the AI system makes decisions without human oversight or intervention during the decision-making process.',
   'governance', 'medium'),
  ('fc-singapore-ai-hi-4', '00000000-0000-0000-0000-000000000001', 'singapore-ai',
   'HI.4', 'Determining the Level of Human Involvement in AI-augmented Decision-Making', 'Human-over-the-loop',
   'A model of oversight in which the AI system makes decisions but a human monitors and can adjust or override the outcome, allowing intervention where events are unexpected or undesirable.',
   'governance', 'medium'),
  ('fc-singapore-ai-hi-5', '00000000-0000-0000-0000-000000000001', 'singapore-ai',
   'HI.5', 'Determining the Level of Human Involvement in AI-augmented Decision-Making', 'Design of the decision-making matrix weighing probability and severity of harm',
   'Use a decision matrix that plots the probability of harm against the severity of harm to select the appropriate level of human involvement for a given AI-augmented decision.',
   'governance', 'medium'),
  ('fc-singapore-ai-om-1', '00000000-0000-0000-0000-000000000001', 'singapore-ai',
   'OM.1', 'Operations Management', 'Good data accountability practices',
   'Adopt good data accountability practices across the AI lifecycle, understanding and documenting how data are collected, used and managed to train, test and operate AI models.',
   'governance', 'high'),
  ('fc-singapore-ai-om-2', '00000000-0000-0000-0000-000000000001', 'singapore-ai',
   'OM.2', 'Operations Management', 'Understanding the lineage of data',
   'Maintain understanding of the lineage of data — the source of data and how it moves through and is transformed within the organisation — to support data quality and accountability.',
   'detective', 'medium'),
  ('fc-singapore-ai-om-3', '00000000-0000-0000-0000-000000000001', 'singapore-ai',
   'OM.3', 'Operations Management', 'Ensuring data quality',
   'Assess and ensure the quality of data used in AI models, considering accuracy, completeness, veracity, recency, relevance, integrity and how the data were prepared.',
   'detective', 'high'),
  ('fc-singapore-ai-om-4', '00000000-0000-0000-0000-000000000001', 'singapore-ai',
   'OM.4', 'Operations Management', 'Minimising inherent bias',
   'Take steps to minimise inherent bias in data and models — for example through dataset heterogeneity and reviewing datasets for unintended discriminatory bias — to promote fair outcomes.',
   'preventive', 'high'),
  ('fc-singapore-ai-om-5', '00000000-0000-0000-0000-000000000001', 'singapore-ai',
   'OM.5', 'Operations Management', 'Different considerations at the stages of algorithm selection and development',
   'Weigh relevant considerations when selecting and developing models and algorithms, balancing commercial objectives against transparency, explainability and the potential impact on individuals.',
   'governance', 'medium'),
  ('fc-singapore-ai-om-6', '00000000-0000-0000-0000-000000000001', 'singapore-ai',
   'OM.6', 'Operations Management', 'Explainability',
   'Strive for explainability so that the way an AI model''s decisions are reached can be understood and explained, ideally in a manner accessible to affected individuals.',
   'technical', 'high'),
  ('fc-singapore-ai-om-7', '00000000-0000-0000-0000-000000000001', 'singapore-ai',
   'OM.7', 'Operations Management', 'Repeatability',
   'Ensure repeatability — the ability to consistently perform an action or make a decision given the same scenario — as a means of building trust in the AI system.',
   'technical', 'medium'),
  ('fc-singapore-ai-om-8', '00000000-0000-0000-0000-000000000001', 'singapore-ai',
   'OM.8', 'Operations Management', 'Robustness',
   'Ensure robustness so that the AI system can cope with errors during execution and erroneous input, and continues to operate reliably under a range of conditions.',
   'technical', 'medium'),
  ('fc-singapore-ai-om-9', '00000000-0000-0000-0000-000000000001', 'singapore-ai',
   'OM.9', 'Operations Management', 'Reproducibility',
   'Ensure reproducibility so that an AI system''s results can be reproduced consistently, supporting validation and troubleshooting of the model.',
   'technical', 'medium'),
  ('fc-singapore-ai-om-10', '00000000-0000-0000-0000-000000000001', 'singapore-ai',
   'OM.10', 'Operations Management', 'Traceability',
   'Build in traceability by keeping records of the data flows, model development and decisions of the AI system, so that its behaviour can be traced and understood.',
   'detective', 'medium'),
  ('fc-singapore-ai-om-11', '00000000-0000-0000-0000-000000000001', 'singapore-ai',
   'OM.11', 'Operations Management', 'Auditability',
   'Support auditability by retaining appropriate documentation and records that allow the AI system and its decisions to be reviewed and assessed by internal or external parties.',
   'detective', 'medium'),
  ('fc-singapore-ai-om-12', '00000000-0000-0000-0000-000000000001', 'singapore-ai',
   'OM.12', 'Operations Management', 'Regular tuning of deployed models',
   'Regularly review and tune deployed AI models so that they remain relevant and accurate as the operating environment, data and objectives change over time.',
   'corrective', 'medium'),
  ('fc-singapore-ai-sc-1', '00000000-0000-0000-0000-000000000001', 'singapore-ai',
   'SC.1', 'Stakeholder Interaction and Communication', 'General disclosure',
   'Provide general disclosure that AI is used in products or services, appropriate to the context, to build public understanding and trust.',
   'administrative', 'high'),
  ('fc-singapore-ai-sc-2', '00000000-0000-0000-0000-000000000001', 'singapore-ai',
   'SC.2', 'Stakeholder Interaction and Communication', 'Policy for interaction with individuals',
   'Establish a policy on how the organisation interacts and communicates with individuals affected by AI, designed to increase public confidence in its use of AI.',
   'administrative', 'medium'),
  ('fc-singapore-ai-sc-3', '00000000-0000-0000-0000-000000000001', 'singapore-ai',
   'SC.3', 'Stakeholder Interaction and Communication', 'Option to opt out',
   'Where practicable and appropriate, provide individuals with the option to opt out of the use of AI in relation to decisions that affect them.',
   'administrative', 'medium'),
  ('fc-singapore-ai-sc-4', '00000000-0000-0000-0000-000000000001', 'singapore-ai',
   'SC.4', 'Stakeholder Interaction and Communication', 'Channels for feedback, queries and decision review',
   'Provide accessible channels for individuals to give feedback, raise queries, and request a review of AI-augmented decisions that affect them.',
   'corrective', 'medium'),
  ('fc-singapore-ai-sc-5', '00000000-0000-0000-0000-000000000001', 'singapore-ai',
   'SC.5', 'Stakeholder Interaction and Communication', 'Acceptable use policy',
   'Set out an acceptable use policy for products and services that use AI, communicating to users the intended use and the conditions under which the AI should and should not be relied upon.',
   'administrative', 'low'),
  ('fc-singapore-ai-sc-6', '00000000-0000-0000-0000-000000000001', 'singapore-ai',
   'SC.6', 'Stakeholder Interaction and Communication', 'Communicating in a manner that is easy to understand',
   'Communicate with individuals about the use of AI in a manner that is clear, easy to understand and tailored to the audience, so that disclosures are meaningful.',
   'administrative', 'low')
ON CONFLICT (id) DO UPDATE SET
  control_ref = EXCLUDED.control_ref, domain = EXCLUDED.domain,
  title = EXCLUDED.title, description = EXCLUDED.description,
  control_type = EXCLUDED.control_type, priority = EXCLUDED.priority;

-- ===========================================================================
-- 5. UNESCO RECOMMENDATION ON THE ETHICS OF AI (2021)
--    4 core values + 10 principles + 11 Areas of Policy Action.
-- ===========================================================================
INSERT INTO public.framework_controls
  (id, org_id, framework_id, control_ref, domain, title, description, control_type, priority)
VALUES
  ('fc-unesco-ai-ethics-value-1', '00000000-0000-0000-0000-000000000001', 'unesco-ai-ethics',
   'Value 1', 'Values', 'Respect, protection and promotion of human rights and fundamental freedoms and human dignity',
   'The inviolable and inherent dignity of every human constitutes the foundation for the indivisible system of human rights and fundamental freedoms, which must be respected, protected and promoted throughout the lifecycle of AI systems.',
   'governance', 'high'),
  ('fc-unesco-ai-ethics-value-2', '00000000-0000-0000-0000-000000000001', 'unesco-ai-ethics',
   'Value 2', 'Values', 'Environment and ecosystem flourishing',
   'Environmental and ecosystem flourishing should be recognised, protected and promoted throughout the lifecycle of AI systems, as a prerequisite for the well-being of present and future generations.',
   'governance', 'high'),
  ('fc-unesco-ai-ethics-value-3', '00000000-0000-0000-0000-000000000001', 'unesco-ai-ethics',
   'Value 3', 'Values', 'Ensuring diversity and inclusiveness',
   'Respect, protection and promotion of diversity and inclusiveness should be ensured throughout the lifecycle of AI systems, consistent with international law, including human rights law.',
   'governance', 'high'),
  ('fc-unesco-ai-ethics-value-4', '00000000-0000-0000-0000-000000000001', 'unesco-ai-ethics',
   'Value 4', 'Values', 'Living in peaceful, just and interconnected societies',
   'AI actors should play a participative and enabling role in ensuring peaceful and just societies, based on an interconnected future for the benefit of all, consistent with human rights and fundamental freedoms.',
   'governance', 'high'),
  ('fc-unesco-ai-ethics-principle-1', '00000000-0000-0000-0000-000000000001', 'unesco-ai-ethics',
   'Principle 1', 'Principles', 'Proportionality and do no harm',
   'The use of AI systems must not go beyond what is necessary to achieve a legitimate aim, and risk assessments should be used to prevent harms that may result from such uses.',
   'preventive', 'high'),
  ('fc-unesco-ai-ethics-principle-2', '00000000-0000-0000-0000-000000000001', 'unesco-ai-ethics',
   'Principle 2', 'Principles', 'Safety and security',
   'Unwanted harms (safety risks) and vulnerabilities to attack (security risks) should be avoided and addressed, prevented and eliminated throughout the lifecycle of AI systems to ensure human, environmental and ecosystem safety and security.',
   'technical', 'high'),
  ('fc-unesco-ai-ethics-principle-3', '00000000-0000-0000-0000-000000000001', 'unesco-ai-ethics',
   'Principle 3', 'Principles', 'Fairness and non-discrimination',
   'AI actors should promote social justice, fairness and non-discrimination while taking an inclusive approach to ensure that the benefits of AI are accessible and available to all.',
   'governance', 'high'),
  ('fc-unesco-ai-ethics-principle-4', '00000000-0000-0000-0000-000000000001', 'unesco-ai-ethics',
   'Principle 4', 'Principles', 'Sustainability',
   'AI technologies should be assessed against their impacts on sustainability, understood as a set of constantly evolving goals including those set out in the UN Sustainable Development Goals.',
   'governance', 'medium'),
  ('fc-unesco-ai-ethics-principle-5', '00000000-0000-0000-0000-000000000001', 'unesco-ai-ethics',
   'Principle 5', 'Principles', 'Right to privacy, and data protection',
   'Privacy must be respected, protected and promoted throughout the lifecycle of AI systems, and adequate data protection frameworks and governance mechanisms should be established in compliance with the law.',
   'technical', 'high'),
  ('fc-unesco-ai-ethics-principle-6', '00000000-0000-0000-0000-000000000001', 'unesco-ai-ethics',
   'Principle 6', 'Principles', 'Human oversight and determination',
   'Member States should ensure that it is always possible to attribute ethical and legal responsibility for any stage of the lifecycle of AI systems to natural or legal persons, and that human oversight of AI systems is retained.',
   'governance', 'high'),
  ('fc-unesco-ai-ethics-principle-7', '00000000-0000-0000-0000-000000000001', 'unesco-ai-ethics',
   'Principle 7', 'Principles', 'Transparency and explainability',
   'The transparency and explainability of AI systems are often essential preconditions to ensure the respect, protection and promotion of human rights, fundamental freedoms and ethical principles, appropriate to the context and impact.',
   'administrative', 'high'),
  ('fc-unesco-ai-ethics-principle-8', '00000000-0000-0000-0000-000000000001', 'unesco-ai-ethics',
   'Principle 8', 'Principles', 'Responsibility and accountability',
   'AI actors and Member States should respect, protect and promote human rights and fundamental freedoms, and should be responsible and accountable, with appropriate oversight, impact assessment, audit and due diligence mechanisms in place.',
   'governance', 'high'),
  ('fc-unesco-ai-ethics-principle-9', '00000000-0000-0000-0000-000000000001', 'unesco-ai-ethics',
   'Principle 9', 'Principles', 'Awareness and literacy',
   'Public awareness and understanding of AI technologies and the value of data should be promoted through open and accessible education, civic engagement, digital skills and AI ethics training, media and information literacy.',
   'administrative', 'medium'),
  ('fc-unesco-ai-ethics-principle-10', '00000000-0000-0000-0000-000000000001', 'unesco-ai-ethics',
   'Principle 10', 'Principles', 'Multi-stakeholder and adaptive governance and collaboration',
   'International law and national sovereignty must be respected in the use of data, and the participation of diverse stakeholders is necessary for inclusive approaches to AI governance and adaptive collaboration.',
   'governance', 'medium'),
  ('fc-unesco-ai-ethics-policy-area-1', '00000000-0000-0000-0000-000000000001', 'unesco-ai-ethics',
   'Policy Area 1', 'Areas of Policy Action', 'Ethical Impact Assessment',
   'Member States should introduce frameworks for ethical impact assessments to identify and assess the benefits, concerns and risks of AI systems, as well as appropriate risk prevention, mitigation and monitoring measures.',
   'detective', 'high'),
  ('fc-unesco-ai-ethics-policy-area-2', '00000000-0000-0000-0000-000000000001', 'unesco-ai-ethics',
   'Policy Area 2', 'Areas of Policy Action', 'Ethical Governance and Stewardship',
   'Member States should ensure that AI governance mechanisms are inclusive, transparent, multidisciplinary, multilateral and multi-stakeholder, incorporating oversight, impact assessment, audit and due diligence.',
   'governance', 'high'),
  ('fc-unesco-ai-ethics-policy-area-3', '00000000-0000-0000-0000-000000000001', 'unesco-ai-ethics',
   'Policy Area 3', 'Areas of Policy Action', 'Data Policy',
   'Member States should develop data governance strategies that ensure the continual evaluation of the quality of training data, security and privacy of data, and appropriate protection of personal data used in AI systems.',
   'governance', 'high'),
  ('fc-unesco-ai-ethics-policy-area-4', '00000000-0000-0000-0000-000000000001', 'unesco-ai-ethics',
   'Policy Area 4', 'Areas of Policy Action', 'Development and International Cooperation',
   'Member States and companies should leverage international cooperation to help low- and middle-income countries benefit from and participate in AI, addressing digital divides, inequalities and technological dependencies.',
   'governance', 'medium'),
  ('fc-unesco-ai-ethics-policy-area-5', '00000000-0000-0000-0000-000000000001', 'unesco-ai-ethics',
   'Policy Area 5', 'Areas of Policy Action', 'Environment and Ecosystems',
   'AI actors and Member States should reduce the environmental impact of AI systems, including their carbon footprint, and use AI to help protect the environment and ecosystems.',
   'governance', 'medium'),
  ('fc-unesco-ai-ethics-policy-area-6', '00000000-0000-0000-0000-000000000001', 'unesco-ai-ethics',
   'Policy Area 6', 'Areas of Policy Action', 'Gender',
   'Member States should ensure gender equality and that AI systems do not reinforce gender gaps or discrimination, promoting the participation and leadership of women and girls in AI and closing gender divides.',
   'governance', 'medium'),
  ('fc-unesco-ai-ethics-policy-area-7', '00000000-0000-0000-0000-000000000001', 'unesco-ai-ethics',
   'Policy Area 7', 'Areas of Policy Action', 'Culture',
   'Member States should encourage AI systems that respect and promote cultural and linguistic diversity, support cultural and creative industries, and safeguard cultural heritage.',
   'governance', 'low'),
  ('fc-unesco-ai-ethics-policy-area-8', '00000000-0000-0000-0000-000000000001', 'unesco-ai-ethics',
   'Policy Area 8', 'Areas of Policy Action', 'Education and Research',
   'Member States should promote the acquisition of AI ethics prerequisite skills, digital and media literacy, and responsible AI research and innovation across all levels of education.',
   'administrative', 'medium'),
  ('fc-unesco-ai-ethics-policy-area-9', '00000000-0000-0000-0000-000000000001', 'unesco-ai-ethics',
   'Policy Area 9', 'Areas of Policy Action', 'Communication and Information',
   'Member States should use AI systems to improve access to information and knowledge, promote quality journalism and reliable information, and counter disinformation while protecting freedom of expression.',
   'governance', 'medium'),
  ('fc-unesco-ai-ethics-policy-area-10', '00000000-0000-0000-0000-000000000001', 'unesco-ai-ethics',
   'Policy Area 10', 'Areas of Policy Action', 'Economy and Labour',
   'Member States should assess and address the impact of AI systems on labour markets and skills requirements, protect the rights and well-being of workers, and support fair transitions.',
   'governance', 'medium'),
  ('fc-unesco-ai-ethics-policy-area-11', '00000000-0000-0000-0000-000000000001', 'unesco-ai-ethics',
   'Policy Area 11', 'Areas of Policy Action', 'Health and Social Well-being',
   'Member States should ensure that AI systems used in health and social care are safe, effective, ethical and evidence-based, protect patient data, and promote physical and mental health and social well-being.',
   'governance', 'high')
ON CONFLICT (id) DO UPDATE SET
  control_ref = EXCLUDED.control_ref, domain = EXCLUDED.domain,
  title = EXCLUDED.title, description = EXCLUDED.description,
  control_type = EXCLUDED.control_type, priority = EXCLUDED.priority;

-- ===========================================================================
-- Count sync + proof
-- ===========================================================================
UPDATE public.frameworks f
SET control_count = (SELECT count(*) FROM public.framework_controls fc
                     WHERE fc.framework_id = f.id
                       AND fc.org_id = '00000000-0000-0000-0000-000000000001')
WHERE f.id IN ('eu-ai-act','gdpr','oecd-ai','singapore-ai','unesco-ai-ethics');

DO $$
DECLARE
  c_eu int; c_gdpr int; c_oecd int; c_sg int; c_unesco int;
BEGIN
  SELECT count(*) INTO c_eu     FROM public.framework_controls WHERE framework_id='eu-ai-act'        AND org_id='00000000-0000-0000-0000-000000000001';
  SELECT count(*) INTO c_gdpr   FROM public.framework_controls WHERE framework_id='gdpr'             AND org_id='00000000-0000-0000-0000-000000000001';
  SELECT count(*) INTO c_oecd   FROM public.framework_controls WHERE framework_id='oecd-ai'          AND org_id='00000000-0000-0000-0000-000000000001';
  SELECT count(*) INTO c_sg     FROM public.framework_controls WHERE framework_id='singapore-ai'     AND org_id='00000000-0000-0000-0000-000000000001';
  SELECT count(*) INTO c_unesco FROM public.framework_controls WHERE framework_id='unesco-ai-ethics' AND org_id='00000000-0000-0000-0000-000000000001';
  RAISE NOTICE 'framework_controls seeded: eu-ai-act=%, gdpr=%, oecd-ai=%, singapore-ai=%, unesco-ai-ethics=%',
    c_eu, c_gdpr, c_oecd, c_sg, c_unesco;
END $$;
