-- Seed: 10 AI GRC Frameworks
TRUNCATE frameworks CASCADE;
INSERT INTO frameworks (id,name,short_name,version,category,issuing_body,jurisdiction,effective_date,control_count,structure,description,url,adopted,coverage_pct) VALUES ('iso-42001','ISO/IEC 42001:2023','ISO 42001','2023','AI Management','ISO/IEC','International','2023-12-18',38,'9 governance areas in Annex A','AI Management System (AIMS) standard providing a structured approach for managing AI risks and opportunities.','https://www.iso.org/standard/81230.html',true,31);
INSERT INTO frameworks (id,name,short_name,version,category,issuing_body,jurisdiction,effective_date,control_count,structure,description,url,adopted,coverage_pct) VALUES ('nist-ai-rmf','NIST AI Risk Management Framework 1.0','NIST AI RMF','1.0','AI Risk Management','NIST','United States','2023-01-26',58,'4 core functions: Govern, Map, Measure, Manage','Voluntary framework to better manage risks to individuals, organizations, and society associated with AI.','https://www.nist.gov/itl/ai-risk-management-framework',true,74);
INSERT INTO frameworks (id,name,short_name,version,category,issuing_body,jurisdiction,effective_date,control_count,structure,description,url,adopted,coverage_pct) VALUES ('eu-ai-act','EU AI Act','EU AI Act','2024','AI Regulation','European Union','European Union','2024-08-01',113,'113 articles, 13 Annexes - risk-based tiers','Regulation laying down harmonised rules on artificial intelligence with risk-based obligations.','https://artificialintelligenceact.eu/',true,71);
INSERT INTO frameworks (id,name,short_name,version,category,issuing_body,jurisdiction,effective_date,control_count,structure,description,url,adopted,coverage_pct) VALUES ('singapore-ai','Singapore Model AI Governance Framework','SG Model AI','2.0','AI Governance','IMDA Singapore','Singapore','2020-01-21',25,'4 pillars: Internal Governance, HITL, Operations, Customer Communication','Framework providing guidance to companies on key ethical and governance issues when deploying AI.','https://www.pdpc.gov.sg/help-and-resources/2020/01/model-ai-governance-framework',true,43);
INSERT INTO frameworks (id,name,short_name,version,category,issuing_body,jurisdiction,effective_date,control_count,structure,description,url,adopted,coverage_pct) VALUES ('owasp-llm','OWASP Top 10 for LLM Applications','OWASP LLM','2025','AI Security','OWASP Foundation','International','2025-01-01',10,'10 primary LLM security vulnerabilities','List of the most critical vulnerabilities often seen in LLM applications.','https://owasp.org/www-project-top-10-for-large-language-model-applications/',true,87);
INSERT INTO frameworks (id,name,short_name,version,category,issuing_body,jurisdiction,effective_date,control_count,structure,description,url,adopted,coverage_pct) VALUES ('oecd-ai','OECD AI Principles','OECD AI','2019','AI Principles','OECD','International','2019-05-22',10,'5 values-based principles + 5 policy recommendations','First intergovernmental standard on AI promoting innovative and trustworthy AI that respects human rights.','https://oecd.ai/en/ai-principles',true,62);
INSERT INTO frameworks (id,name,short_name,version,category,issuing_body,jurisdiction,effective_date,control_count,structure,description,url,adopted,coverage_pct) VALUES ('gdpr','General Data Protection Regulation','GDPR','2016/679','Data Protection','European Union','European Union','2018-05-25',99,'99 Articles + Recitals; Art. 22 (automated decisions), Art. 35 (DPIA)','EU regulation on data protection and privacy for all individuals within the EU and EEA.','https://gdpr-info.eu/',true,89);
INSERT INTO frameworks (id,name,short_name,version,category,issuing_body,jurisdiction,effective_date,control_count,structure,description,url,adopted,coverage_pct) VALUES ('unesco-ai-ethics','UNESCO Recommendation on the Ethics of AI','UNESCO AI Ethics','2021','AI Ethics','UNESCO','International','2021-11-23',11,'11 Areas of Policy Action','First global standard-setting instrument on the ethics of AI adopted by 193 Member States.','https://www.unesco.org/en/artificial-intelligence/recommendation-ethics',true,48);
INSERT INTO frameworks (id,name,short_name,version,category,issuing_body,jurisdiction,effective_date,control_count,structure,description,url,adopted,coverage_pct) VALUES ('google-saif','Google Secure AI Framework','Google SAIF','1.0','AI Security','Google','International','2023-06-08',6,'6 core pillars','Conceptual framework for secure AI systems focusing on security practices.','https://safety.google/cybersecurity-advancements/saif/',true,49);
INSERT INTO frameworks (id,name,short_name,version,category,issuing_body,jurisdiction,effective_date,control_count,structure,description,url,adopted,coverage_pct) VALUES ('mitre-atlas','MITRE ATLAS','MITRE ATLAS','2024','AI Threat Modeling','MITRE Corporation','International','2023-07-01',30,'~30 Tactics/Techniques mapped like ATT&CK','Adversarial Threat Landscape for Artificial-Intelligence Systems - globally accessible knowledge base.','https://atlas.mitre.org/',true,51);