import { Warning, Plus, MagnifyingGlass } from '@phosphor-icons/react';
import { useMemo } from "react";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '../../components/ui/table';
interface Props { open: boolean; onClose: () => void; }
interface Gap { control: string; required: string; current: string; gap: "high"|"medium"|"low"; }
export default function GapAnalysisModal({ open, onClose }: Props) {
  const gaps = useMemo<Gap[]>(() => [{control:"Data Privacy",required:"Full PIA",current:"Partial PIA",gap:"medium"},{control:"Model Documentation",required:"Model Card v2",current:"None",gap:"high"},{control:"Bias Testing",required:"Monthly",current:"Quarterly",gap:"low"}],[]);
  if (!open) return null;
  const gapColors = {high:"bg-red-100 text-red-800",medium:"bg-yellow-100 text-yellow-800",low:"bg-green-100 text-green-800"};
  return (<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50" onClick={onClose}><div className="bg-[hsl(var(--background))] rounded-none p-6 w-[600px] max-h-[80vh] overflow-auto shadow-xl" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==="Escape")onClose()}} tabIndex={-1}><h2 className="text-xl font-bold mb-4">Gap Analysis</h2><Table className="w-full border-collapse text-foreground"><TableHeader><TableRow className="border-b"><TableHead className="text-left p-2">Control</TableHead><TableHead className="text-left p-2">Required</TableHead><TableHead className="text-left p-2">Current</TableHead><TableHead className="text-left p-2">Gap</TableHead></TableRow></TableHeader><TableBody>{gaps.map((g,i)=>(<TableRow key={i} className="border-b"><TableCell className="p-2">{g.control}</TableCell><TableCell className="p-2">{g.required}</TableCell><TableCell className="p-2">{g.current}</TableCell><TableCell className="p-2"><span className={`px-2 py-1 rounded text-xs ${gapColors[g.gap]}`}>{g.gap}</span></TableCell></TableRow>))}</TableBody></Table><div className="flex justify-end mt-4"><button className="px-4 py-2 border rounded" onClick={onClose}>Close</button></div></div></div>);}
